### ISSUE TITLE
qddt exception

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#101]
# QDDT version  b0f5371

made changes that make sure that name has a value when saved to the DB.
# Request

/responsedomain/page/search?ResponseKind=SCALE
# Exception

Could not write content: (was java.lang.NullPointerException) (through reference chain: org.springframework.hateoas.PagedResources["content"]->java.util.UnmodifiableCollection[0]->org.springframework.hateoas.Resource["content"]->no.nsd.qddt.domain.responsedomain.ResponseDomain["managedRepresentation"]->no.nsd.qddt.domain.category.Category["name"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.springframework.hateoas.PagedResources["content"]->java.util.UnmodifiableCollection[0]->org.springframework.hateoas.Resource["content"]->no.nsd.qddt.domain.responsedomain.ResponseDomain["managedRepresentation"]->no.nsd.qddt.domain.category.Category["name"])

**Comment by StigNorland** [comment]
database has been updated to fix this error,
