### ISSUE TITLE
Reuse/basedon functionality 

### ISSUE THREAD

**Issue by sarah-city** [DASISH/qddt-client#107]
**Query from ESS HQ:** 
When something is created as “newbasedon” it is not immediately apparent what the link between the new and the original element is.  How will this connection be shown within the tool/element history?

**Proposal from Hilde:**  (5th Aug) 
Use rationale codes: ResusebyCopy, Translations, SourceBasedon

**Response from HQ:** 
Our question was not so much about different rationales for selecting “NewBasedon” but about how /where the link between the “NewBasedon” element and the original element would be displayed within the tool.   

We can see that it might be useful to develop different rationale codes for “basedon”.    However, I’m not exactly clear what the meaning of the codes proposed are. Please could you clarify? 

Translations won’t be stored within the QDDT, only the English source questions.    Versioning of 
translations (which we agreed under DASISH would be “basedon”) is an issue for the TMT? 

Scenarios under which we may want to use the “basedon” functionality:  
• Repeating a question across ESS rounds – e.g. core items, items in repeat modules.  
This would be “ReusebyCopy”?  

NB:  For an ESS item to count as a repeat it is the full question as construct, not just the question item that needs to be repeated (though its exact position in the questionnaire may differ slightly) 

NB2:  We discussed in Bergen that we would like to be able to create repeat modules by copying the whole module from a previous round (study) and then potentially dropping unwanted items, rather than having to build up a repeat module one item at a time.    Will this be possible? 

• Adding new subconcepts/items within a battery.   

For e.g. in the R7 immigration module the “Opposition to immigration” concept has 7 items asking about opposition to different groups which follow the same question structure/use the same response domain.  Four of these items are repeats from Round 1 whilst three are new items added for Round 7.

Would we count the new items as “newbasedon” the previous items in the battery or just “new”?

There may be other scenarios I haven’t thought of….?

**Comment by hildeorten** [comment]
Needs further discussion

**Comment by StigNorland** [comment]
closing this as it is now part of Concept reference solution
