### ISSUE TITLE
Question Items: Add concept

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#111]
The concept(s) should be added to the menu Question Items when editing the Question Item. I suggest displaying the referenced Concept Name(s) in addition with a magnifier which opens a popup window with the details of the referenced concept.

**Comment by liuy97** [comment]
Referencing concepts is not supported by the backend, [wiki](https://github.com/DASISH/qddt-client/wiki/Api-ref). It will not be implemented at frontend until the backend supports it. I will remove this issue in #119.

**Comment by StigNorland** [comment]
concept/list/by-QuestionItem/{qiId} will be added shortly

**Comment by StigNorland** [comment]
Should be ready now.

**Comment by liuy97** [comment]
@StigNorland ,

Request
<code>
https://qddt.nsd.no/api/concept/list/by-QuestionItem/7f000101-560d-1538-8156-11a865bf00ae
</code>
Response
<code>
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Aug 24 13:24:07 CEST 2016</div><div>There was an unexpected error (type=Not Found, status=404).</div><div>Not Found</div></body></html>
</code>

**Comment by StigNorland** [comment]
I have updated the sourcecode, not qddt.nsd.no
Tomorrow qddt.nsd.no will be updated, maybe best to keep  a local copy and service going ?

**Comment by liuy97** [comment]
After you updated the backend, I cannot run the backend in my local machine. If possible, update the backend at qddt.nsd.no.

**Comment by StigNorland** [comment]
Ah, that is because of the database changes that I have  manually updated on the server, in order to preserve the data there.
You can fix this by updating line 6 in application.properties
spring.jpa.hibernate.ddl-auto=validate -> change to update might fix that 
(do that locally)

**Comment by liuy97** [comment]
It does not work here. I have deleted all of the tables. They are not created by the backend. I will wait for the latest backend at qddt.nsd.no to continue this issue.

**Comment by StigNorland** [comment]
then use "create-drop" instead of "update" or "validate".

**Comment by liuy97** [comment]
No, it does not work, too.

**Comment by StigNorland** [comment]
any errormessages that indicate what the problem might be?

**Comment by liuy97** [comment]
Ok, the problem is finally identified in application.properties Line 11, not 127.0.0.16
<code>
spring.datasource.url=jdbc:postgresql://127.0.0.16:5432/postgres
</code>

**Comment by BenjaminNSD** [comment]
Cannot see the Concept in QuestionItem. 
Example: Question "Where do you live now?" should have a ConceptReference to Concept "Beliefs about welfare state sustainability"

Can you assist?
http://liuy97.github.io/Questions

**Comment by liuy97** [comment]
I have not updated my site. The backend have to be updated firstly.

**Comment by BenjaminNSD** [comment]
When the issue is closed the issue it should be ready for testing. Sarah and Virginia expect this to be working when the issues is closed and labeled as mileston 26. september. 

Can you either update the site or change the status to open?

**Comment by liuy97** [comment]
The short answer is no. It depends on the backend. What's the correct way is to confirm updating the backend, otherwise you have gotten errors. This issue has been fixed. If have any errors, then you can open it.

**Comment by BenjaminNSD** [comment]
For the people testing the tool it doesn’t matter where the problem lies. Issues which regards functionality/layout etc. can first be closed when you are sure that it will work in tool-release connected to the milestone.

Please re-open the issue (agreed by Knut)

**Comment by liuy97** [comment]
So It means you need to open it. You can do it by yourself anyway.

**Comment by BenjaminNSD** [comment]
Instead of a magnifier we could rather underline the ConceptName and highlight the Name in blue to emphasize that there is a clickable link to the concept referred to the question.

Example Name: "Beliefs about welfare state sustainability" (underlined and in blue colour)

**Comment by liuy97** [comment]
It's better to create a new issue.

**Comment by BenjaminNSD** [comment]
You're right. I added a layout suggestion to #114

**Comment by BenjaminNSD** [comment]
it works now (closed),

@StigNorland 
the milestone should be changed back to 26 aug since it was part of the 26 aug release
