### ISSUE TITLE
In Concepts: add magnifier to display question details to referenced question to display details

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#114]
In Concepts:
Questions which are linked to concepts can currently only be removed. We should add magnifier to display question details to referenced question to display details as we do it in QuestionItems when viewing the concept

**Comment by BenjaminNSD** [comment]
Instead of a magnifier we could rather underline the QuestionItemName and highlight the Name in blue to emphasize that there is a clickable link to the question attached to the concept.

Example: TRSTPRT,  TRSTPRL, TRSTPRL (underlined and in blue colour)

**Comment by liuy97** [comment]
Is a pop window still used here?

**Comment by BenjaminNSD** [comment]
yes. Layout could be similar to questions when you click on magnifier for the concept

**Comment by liuy97** [comment]
Questionitem window poping up from concept will disable editing response domain. The reason is that poping up window does not work from a popup window. Another reason is consuming too much memory. Popup window comes from 3rd party library(material css).
