### ISSUE TITLE
Issue priority at front end

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#119]
@hildeorten, @BenjaminNSD

The issues will be implemented according to the the following priority, where the priority is descending sort.
#99
#121
#124
#110,
#109,
#108,
#107,
#98

The implemented issued will be removed here. Each task related to the front end should begin from a new issue.

**Comment by BenjaminNSD** [comment]
Please add #120 as priority one.

**Comment by BenjaminNSD** [comment]
Please add #121 as priority one.

**Comment by liuy97** [comment]
close this, week milestone is used now.

**Comment by BenjaminNSD** [comment]
For the people testing the tool it doesn’t matter where the problem lies. Issues which regards functionality/layout etc. can first be closed when you are sure that it will work in tool-release connected to the milestone.

Please re-open the issue (agreed by Knut)
