### ISSUE TITLE
Access to question items

### ISSUE THREAD

**Issue by virginia-ros** [DASISH/qddt-client#123]
It's not possible to access the question items through the concepts - where the concepts are developed

**Comment by liuy97** [comment]
What does **access** mean?

**Comment by virginia-ros** [comment]
It is possible to edit/change question items - accessing them from the main menu - but the changes are not saved at the back end

**Comment by virginia-ros** [comment]
@liuy97 When we click on the question item if we are on the concepts screen we cannot see them so to edit them we have to go to the main menu an edit them there

**Comment by liuy97** [comment]
Do you want to preview question text and response domain?

**Comment by virginia-ros** [comment]
Yes, but also to be able to edit them (more pop-ups, maybe?)
