### ISSUE TITLE
Tree of contents

### ISSUE THREAD

**Issue by virginia-ros** [DASISH/qddt-client#124]
Would it be possible to increase the denting in the tree of contents for second and third levels to make more clear where we are? 

I guess this is for @liuy97 but I'm not sure :)

**Comment by liuy97** [comment]
Yes. All of the layout problems can be assigned to me.

Question: How much denting do you need?

**Comment by virginia-ros** [comment]
Not sure really, enough to make the different levels more clear at first glance. Can we also use different layout for the levels (for instance bold and slightly bigger letters for the first level) ?

**Comment by liuy97** [comment]
Yes, I can try do some adjustments according to your description.

**Comment by virginia-ros** [comment]
Thanks :)

**Comment by BenjaminNSD** [comment]
@liuy97 
Please reopen issue
Please increase the denting in the Concept Toc even more to distinguish between the different hierarchy levels.

**Comment by liuy97** [comment]
Please describe it in detail. For example, horizontal denting or vertical denting, how much denting is "more"?

**Comment by BenjaminNSD** [comment]
Same denting as now, move subconcepts just a bit to the right (size of two letters)
