### ISSUE TITLE
Layout improvements:

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#127]
Attached you will find several layout improvements in different sections of the tool.

The issue has also priority 1.
[Change_Buttons.docx](https://github.com/DASISH/qddt-client/files/434493/Change_Buttons.docx)
[edit_QuestionItem.docx](https://github.com/DASISH/qddt-client/files/451548/edit_QuestionItem.docx)

[edit_CodeDomain.docx](https://github.com/DASISH/qddt-client/files/456162/edit_CodeDomain.docx)

[edit_Missing_schemes.docx](https://github.com/DASISH/qddt-client/files/432371/edit_Missing_schemes.docx)
[edit_ScaleDomain.docx](https://github.com/DASISH/qddt-client/files/432369/edit_ScaleDomain.docx)

**Comment by BenjaminNSD** [comment]
[layout_QI5.docx](https://github.com/DASISH/qddt-client/files/426906/layout_QI5.docx)
[layout_3.docx](https://github.com/DASISH/qddt-client/files/426908/layout_3.docx)
[layout_QI.docx](https://github.com/DASISH/qddt-client/files/426909/layout_QI.docx)
[layout_QI2.docx](https://github.com/DASISH/qddt-client/files/426910/layout_QI2.docx)
[layout_QI4.docx](https://github.com/DASISH/qddt-client/files/426907/layout_QI4.docx)

**Comment by BenjaminNSD** [comment]
edit_QuestionItem.docx has been updated. Please remove the NEW-button from CodeDomain

**Comment by liuy97** [comment]
@BenjaminNSD ,
What's the alignment button in edit_questionitem.docx?

**Comment by BenjaminNSD** [comment]
See below!

![alignment](https://cloud.githubusercontent.com/assets/20127077/18267968/fa7ce8f4-7421-11e6-9f91-2c4db58a5cbf.PNG)

**Comment by liuy97** [comment]
1. Do you need to align to distance between each anchor number and ignoring the readable feature of anchor labels?
2. The backend has not supported direction of domains. As a result, I can keep it in scale domain same as the moment, or delete it. What you described will be not implemented in this issue. You can create a new issue for it.

**Comment by BenjaminNSD** [comment]
1. No. The distance should be the same between all numbers in the scale. Usually we don't have more than 2 anchor points. Would be nice if it would be possible to read the 2 anchors and still have the same distance between the numbers. If not, we leave the layout at the moment as it is
2. @hildeorten Hilde. Do you know the requirements regarding scale alignment in backend? We can create new issue regarding this

**Comment by liuy97** [comment]
1. I will leave the UI same as the moment. Although you mentioned there are less than two anchor points at most cases, all of cases have to be supported at the front end. The length of anchor labels are unpredictable.

**Comment by hildeorten** [comment]
1. I agree.
2. BB and HO will make an issue regarding alignment possibilities in
   back end, only for ScaleDomain

liuy97 skrev den 06.09.2016 11:29:

**Comment by liuy97** [comment]
@BenjaminNSD ,

In edit_CodeDomain.docx:
1. Is it only applied to UI of code domain?
2. will it not distinguish the difference of incorrect input, no found element and creating a new category? Any text without matching categories will result in a new one.

**Comment by BenjaminNSD** [comment]
1. Right now I can't find other examples where button is too far from number. So yes
2. With help of the filter the problem will be little. It's ok when any text without matching categories will result in a new one (as long as the user is warned with the red highlighted color)

**Comment by liuy97** [comment]
scale alignment will not be implemented, as said before. close this issue.

**Comment by BenjaminNSD** [comment]
Regarding Change_Buttons.docx
In concepthierarchy: when a question is linked to a concept, the question can currently be detached with the delete button. This button should be replaced with a remove-button (-) since we are not deleting the QuestionItem, just detaching.
