### ISSUE TITLE
Improve "Time stamp option" including compare to previous versions

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#135]
1.  Remove editing-information (example: “Wed Jul 20 2016 by admin@NSD-qddt”) from all elements with time stamp option
2.  Add modifiedBy to time stamp
3.  Information / details available when clicking on the version number like 1.0 and 1.1. and 2.0. Only business versions should be displayed by default. Can implement a button to view revisions.
4.  Add Compare button: show result after clicking button. Highlight the differences in color.

See attachment:
[timestamp.docx](https://github.com/DASISH/qddt-client/files/461456/timestamp.docx)

**Comment by hildeorten** [comment]
@liuy97 please implement compare fields for each element as below:
1.  Category: Label, Description
2.  Response Domains: 
   a) Scale domain: Name, Description, Start, End, Display Layout, Code, Categorylabel
   b) Code domain: Name, Description, Number of codes, Code, Categorylabel
   c) Numeric domain: Name, Description, Low, High
   d) text domain: Name, Description, Min length, Max length
3. Concept: Name, Description
4. Question Item: Name, Question Text, Question Intent, Conceptname+version [clickable link to display concept details), ResponseDomainName+version [clickable link to display response domain details)

**Comment by liuy97** [comment]
@BenjaminNSD 

`Conceptname+version [clickable link to display concept details)`
which cannot be supported for comparison at the moment. The frontend cannot get information which revision of questionitem use which revision of concepts.

**Comment by BenjaminNSD** [comment]
@liuy97 
OK. Hilde and me will discuss that. In the meantime you can continue without Conceptname+version- comparison in QuestionItem.

**Comment by BenjaminNSD** [comment]
@StigNorland what is the problem in the backend here? In principle it should be able to track the relation between questionitems and concepts (including versions)

**Comment by BenjaminNSD** [comment]
I make an additional issue about the implementation of clickable links

**Comment by liuy97** [comment]
Deploy this implementation for this issue as well.
