### ISSUE TITLE
QuestionItem: Input / edit QuestionText: increase input length. Applies also to Category Label

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#139]
1. QuestionItem: Long QuestionText when creating (NEW) or editing a QuestionItem cannot be viewed properly. Please increase the input and make it visible as for Description in Concepts
2. Categories: Same problem. Please increase label length as for Description

**Comment by StigNorland** [comment]
```
/// QuestionIntent: what the question is supposed to gather information about.
@Column(name = "intent", length = 2000)
private String intent;

/// QuestionText: the actual question to ask.
@Column(name = "question", length = 1500)
private String question;
```
