### ISSUE TITLE
Remove redundant windows in questions, categories and response domains

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#140]
Please remove redundant windows in questions and categories. For response domains it should be similar. Please see issue #130. Clicking the magnifier should lead the user to the details. Please see attachment.

[remove_windows.docx](https://github.com/DASISH/qddt-client/files/451824/remove_windows.docx)

**Comment by liuy97** [comment]
Are Column Version, Agency, Modified and modifiedBy deleted?

**Comment by liuy97** [comment]
@BenjaminNSD , have a look at the above question.

**Comment by BenjaminNSD** [comment]
No, don't remove columns!
