### ISSUE TITLE
Left menu harmonization

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#145]
Except for Home, all other entries should link to a gridview of the elements that is displayed.
(missing values and domain needs to be updated)

**Comment by BenjaminNSD** [comment]
For domain issue already exists:
 #130 See attachment for more information.
[Layout ResponseDomain.docx](https://github.com/DASISH/qddt-client/files/463760/Layout.ResponseDomain.docx)

**Comment by liuy97** [comment]
Implement a missing table and update my site. After #147 has been fixed, the related fix will be committed.
