### ISSUE TITLE
problems of Stig commits today

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#147]
Your latest three merges have reset the source codes which will influence a lot of fixes.

**Comment by StigNorland** [comment]
why can't you use hipchat, to do actual chatting...
And Yes sorry for that, I am trying to revert the whole tree back to your latest commit

**Comment by liuy97** [comment]
What you did has introduced a bug. The issue system is used for it.

**Comment by StigNorland** [comment]
bug? I overwrote a lot of files, that is not a bug, that is an error.

**Comment by liuy97** [comment]
Then do you want not to reset you merge?

**Comment by liuy97** [comment]
I have updated my site [liuy97](http://liuy97.github.io/), built from the latest code. You can check it by yourself.

**Comment by liuy97** [comment]
@StigNorland 
The difference between your merge and my last commit is as follows:
https://github.com/DASISH/qddt-client/compare/0e95443...devel
You can see a lot of differences there.

Why do you merge codes into branch skipmerge? what's merged?
