### ISSUE TITLE
Demo disappeared from toolet

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#150]
@liuy97 
The Demo has disappeared from http://liuy97.github.io/ after latest release.

Can you get it back?

**Comment by liuy97** [comment]
see #147, this build is for that bug. Before it is fixed, it will not get update. However, you can continue to test it from my local manchine [ip](http://129.177.92.97/) before the official release.

**Comment by liuy97** [comment]
Issue #147 has been discussed well. So I have updated [liuy97](http://liuy97.github.io/) for demo.
