### ISSUE TITLE
Missing values: Fields and design

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#154]
Fields in Missing values:
1. Name (not label)
2. Description
3. Number of categories

Design: 
Use same design as for codedomain. Number of categories should appear above Type of change etc.

@liuy97

**Comment by liuy97** [comment]
Missing values are category scheme. So they cannot be assigned values at this UI.

**Comment by BenjaminNSD** [comment]
Maybe a mutual misunderstanding. The design should be similar to codedomain, but the 3. field should be: Number of categories (instead of number of codes in codedomain)

**Comment by BenjaminNSD** [comment]
[missing_fields.docx](https://github.com/DASISH/qddt-client/files/474553/missing_fields.docx)

see screenshot
