### ISSUE TITLE
QuestionItem in popupwindow: move dismiss button

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#157]
The dismiss-button in popup-window in QuestionItem (within the concept hierarchy) should be moved to the upper-right corner

@liuy97

**Comment by BenjaminNSD** [comment]
![dismiss_button](https://cloud.githubusercontent.com/assets/20127077/18576901/c7aa461c-7be5-11e6-8b22-71d9a4c21943.PNG)

**Comment by liuy97** [comment]
use "close" icon in stead of "dismiss"
