### ISSUE TITLE
Bug in timestamp/versioning

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#162]
I have just entered and versioned a category. The version sytem creates wrong version numbers:

1.0 - 2.0 - 1.1

See screenshot
![timestamp_error](https://cloud.githubusercontent.com/assets/20127077/18741064/6a506cc2-80ad-11e6-997d-ea9c062621ea.PNG)

**Comment by hildeorten** [comment]
@StigNorland Currently 'Work in progress' saves are stored with the last used business version RationaleCode and is given a new business version, based on the previously used code. Concept and ScaleDomain is tested for this today. Other elements not yet tested for this.

**Comment by StigNorland** [comment]
That is because the front end doesn't use the returned saves in it's local store, meaning that any changes made on the server is overridden by the next save from the client.

To solve this, the client has to update it's local copy of **any object** to **every save** made.

**Comment by liuy97** [comment]
Go to "Feel happy", I get the same result which is not because of updating local objects.
![screenshot from 2016-10-27 10-45-39](https://cloud.githubusercontent.com/assets/2961144/19760587/ab634428-9c32-11e6-80bf-41e1821a69cb.png)

**Comment by StigNorland** [comment]
look at the return value from the first post, is says version 2.0
when you post again, you send version 1.0
![skjermbilde 2016-10-27 11 09 35](https://cloud.githubusercontent.com/assets/3939393/19761406/1ce1fbdc-9c36-11e6-8f70-07521dee969f.png)

**Comment by StigNorland** [comment]
Any changes made to the object on the server is not updated on the client.
if you did, the grid would also show the newly inserted element. 
Now we need to manually refresh the element list to get the changes from the server again.

**Comment by hildeorten** [comment]
@liuy97 

Hi I tested categories again and found that the version numbering now seems to work. However there is some problem with the rationale code (Reason) when choosing 'Save as work in progress' after a business version, please see the attached
[Versioning reason error.pdf](https://github.com/DASISH/qddt-client/files/568494/Versioning.reason.error.pdf)

**Comment by liuy97** [comment]
What you reported is not related to this issue.

**Comment by liuy97** [comment]
Refs #205 , close this issue.
