### ISSUE TITLE
Let QuestionConstruct point to specific QuestionItem business version

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#165]
It should be made possible to let QuestionConstruct (the question as in the instrument) reference a specific business version of the QuestionItem. More than one version of the same QuestionItem can then be used by the same instrument.

**Comment by StigNorland** [comment]
Added field to hold revisionnumber to ControlConstruct (QuestionConstruct)
QuestionItem needs to be fetched manually, in order to force this I have changed backend so that questionitem isn't included when fetching a CC (QC)
