### ISSUE TITLE
Publication status vocabulary

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#167]
@StigNorland Please facilitate for publication status as described in the attached document. Publication status is a CV that goes to UserAttribute pair in DDI
[Publication status in the QDDT.docx](https://github.com/DASISH/qddt-client/files/497537/Publication.status.in.the.QDDT.docx)

**Comment by StigNorland** [comment]
1)  In the current version of the QDDT each save results in a new revision. Each save can contain multiple changes to an element. Save types are ‘work in progress’, ‘version’, ‘new-based on’ and ‘new’.
2)  Some elements can be published. This applies typically to Studies, Modules, Instruments, Concepts, QuestionItems and QuestionConstructs.
3)  The publications can be internal or external and for different purposes.
4)  Publication status codes (UserAttributePair in DDI) should be used to document the purpose of the publication of versions of elements.
5)  Only business versions will be published, not revisions/saves of work in progress.
6)  It should be possible to publish the same version of an element for different purposes (= add multiple publication keys over time for each business version).
7)  DDI: An addition of a publication status key to an element does not trigger a new version of the object (administrative metadata). 
8)  Publication should be dealt with independently of versioning. 
9)  Along with 1), a save of a publication key to an element will trigger a new revision of the object if this is the only change from the original element this should now automatically be updated to count as the business version. 
10) Saves of changes to ‘payload’ metadata as work in progress should be avoided after an element has been published, as the element version then needs to be stable for reference.
11) Any saves of an element as work in progress or a new version that happens after the publication of a version should not ‘inherit’ the publication status keys of the former published business version. However, the same version can be published multiple times, for multiple purposes (see 5)).

**Comment by StigNorland** [comment]
This is now implemented
