### ISSUE TITLE
qddt release 12.04.16: Navigation in concepts under menu Concept Toc

### ISSUE THREAD

**Issue by kksnsd** [DASISH/qddt-client#17]
The menu on the right-hand side should list all Complex (parent) and sub (child) concepts in a module, for navigating between concepts while working on the concept level

**Comment by liuy97** [comment]
fixed at [ e26c9c229d](https://github.com/DASISH/qddt-client/commit/e26c9c229d0bcb83ef3b33c25bb092b48d12a85f)
