### ISSUE TITLE
Make new questions from concepts

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#174]
Please add the elements below when making new questions from the concepts:

![new_qi](https://cloud.githubusercontent.com/assets/20127077/19190777/aa41a2d0-8c9f-11e6-88e3-609c449d2204.PNG)

@liuy97

**Comment by liuy97** [comment]
@BenjaminNSD ,

Do you need to create a new response domain here?

**Comment by BenjaminNSD** [comment]
We actually want to reuse response domain only here, not create new response domains
