### ISSUE TITLE
Display error in current version

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#175]
![view](https://cloud.githubusercontent.com/assets/20127077/19191438/bce31f4c-8ca2-11e6-8205-e0b6d54ca826.PNG)

**Comment by liuy97** [comment]
https://github.com/InfomediaLtd/angular2-materialize/issues/106

I confirm that this is a bug from third party library.

**Comment by liuy97** [comment]
It can be fixed by removing Class "input-field" to some extent. The animation effect will be lost.
