### ISSUE TITLE
Clickable link: definition

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#177]
See attachment:
[clickable link.docx](https://github.com/DASISH/qddt-client/files/523892/clickable.link.docx)
#135
#136

**Comment by liuy97** [comment]
@BenjaminNSD ,

Do all of the clickable qddt elements use URL links to popup windows? We use the button to trigger popup window at the moment, such as response domains from a question item UI.

**Comment by BenjaminNSD** [comment]
Yes, I think so.

Please note that the elements when clicking on the link should not be edibale in the popup window!

**Comment by liuy97** [comment]
For example in questionitem, do you want to replace button with clickable links or  add  new clickable links? 
![screenshot from 2016-10-26 12-44-09](https://cloud.githubusercontent.com/assets/2961144/19723134/38aa975a-9b7a-11e6-8f2c-a0b9c3863862.png)
![screenshot from 2016-10-26 12-44-51](https://cloud.githubusercontent.com/assets/2961144/19723146/3fd25888-9b7a-11e6-8138-314d00897697.png)

**Comment by BenjaminNSD** [comment]
I will discuss that with Hilde in a few minutes

**Comment by BenjaminNSD** [comment]
We don't want to replace the magnifier-button now. The clickable link should primarly used for the usd-by option.

**Comment by liuy97** [comment]
So this issue should be closed, which is reduplicated in #136.
