### ISSUE TITLE
Bug in Timestamp compare: Codelist without codes 

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#179]
Codes in codelist are not displayed in compare. Yong says no codes are returned by the backend.

![codecompare](https://cloud.githubusercontent.com/assets/20127077/19342952/64677bce-9134-11e6-92f2-600d15e4b1cd.PNG)

**Comment by liuy97** [comment]
I confirmed that the elements, which are returned by requesting revisions, have empty codeValues.

**Comment by StigNorland** [comment]
There is a bug in the enver system, working on it.

**Comment by StigNorland** [comment]
Codes are now in place for revisions, which is good 
Database needs to be updated in order for this to work

**Comment by StigNorland** [comment]
see also 
https://github.com/DASISH/qddt-client/issues/261
