### ISSUE TITLE
Replace responsedomain for a questionietem from the concepthierachy

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#186]
Currently we can't detach and attach a responsedomain in questionitem in the concept window (when you click the magnifier of the questionitem as below in the picture). We need to do that.

![responsedomain_attach](https://cloud.githubusercontent.com/assets/20127077/19475179/11e80122-9533-11e6-92e3-91c363daa293.PNG)

**Comment by liuy97** [comment]
Open editing domain from a modal dialog. However, it will not work. The reason is given in #114.
