### ISSUE TITLE
QuestionItem: Remove Concept-button

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#187]
Remove concept button. Instead implement concept into question details by default (as in screenshot below)
'
![concept_button](https://cloud.githubusercontent.com/assets/20127077/19475361/045b3a64-9534-11e6-8baa-1eec0e83b66d.PNG)

**Comment by StigNorland** [comment]
Use a expandable section, which load when expanded.

**Comment by liuy97** [comment]
@BenjaminNSD,

Do you agree with Stig's suggestion?

**Comment by StigNorland** [comment]
http://materializecss.com/collapsible.html
