### ISSUE TITLE
exception when creating a mixed domain

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#190]
https://dasish.github.io/qddt-client/Questions

select one question, such as "How old are you", then add a scale domain and a missing. An exception will happen when creating a mixed domain.

```
no.nsd.qddt.domain.code.Code; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: no.nsd.qddt.domain.code.Code
```

**Comment by StigNorland** [comment]
Saving a Category-hierarchy will not save any codes, as they simply donæ't belong to Categories in the first place, only when you save a responsedomain will the codes be saved (they belong to the responsedomain in the model and the managed Representation in the DDI model)
reason for that is a long story...

**Comment by liuy97** [comment]
Did you test it? I said it happened when creating a mixed domain. The mixed category has been created.

**Comment by StigNorland** [comment]
@liuy97 
You can assign this property regardless of kind (only Scale uses it for now) or else the new responsedomain will loose this property and alginment
newRd.DisplayLayout = old.getDisplayLayout
