### ISSUE TITLE
Questionitem: Insert 'bryt tekst' (break text) in QuestionText

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#191]
Currently text lines can be too long to view in one window/page
Please insert 'bryt tekst' (break text) in QuestionText

**Comment by liuy97** [comment]
Do you mean that the question text is too long in the table of Questionitem? How long do you prefer?

**Comment by hildeorten** [comment]
Yes, Sarah pointed to that. I think 65 signs including blancs would be good. Please see question B1a in http://www.europeansocialsurvey.org/docs/round7/questionnaire/ESS7_source_main_questionnaire_final_alert_03.pdf

**Comment by BenjaminNSD** [comment]
No, question text in table QuestionItem is fine. You two talk about different things. In questions (left menu) question text works (has break text). 

Sarah refers to "Add new question item" in concept window. There we must implement break text.

**Comment by BenjaminNSD** [comment]
![newqi](https://cloud.githubusercontent.com/assets/20127077/19480746/db82385a-954b-11e6-868c-ccbed82b9ce0.PNG)

**Comment by liuy97** [comment]
@BenjaminNSD,

The field you tested is "name". Has the name field the same requirement of the text wrap?

**Comment by BenjaminNSD** [comment]
Oh, I see. I wanted to test Question Text. Name is usually not as long as question text. So there's no need for that, but in general this could be a standard for all fields with text input.
