### ISSUE TITLE
QuestionItem: display responsedomain in table

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#199]
![rp_in_qi](https://cloud.githubusercontent.com/assets/20127077/19727697/c4f3da30-9b90-11e6-85ca-32513c287019.PNG)

**Comment by liuy97** [comment]
When do so, the backend will report the following exception. The unique name is required.

```
  "exceptionMessage" : "could not execute statement; SQL [n/a]; constraint [unq_responsedomain_name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
```

**Comment by StigNorland** [comment]
Now the back end support reusing names as long as the managed representation is not the same.
