### ISSUE TITLE
Response domains: Scaledomain: search is now case-sensitive

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#200]
When searching for "Test_StronglyAgree" we have to type Uppercase T

haven't tested other responsedomaintypes

**Comment by liuy97** [comment]
Refs #176, it's a problem from the backend.

**Comment by StigNorland** [comment]
responsedomain searches have never been case insensetive, and it is he same for all responsdomains.
It will be fixed in todays release.
