### ISSUE TITLE
Page layout in Study, Survey, Module and QuestionItem

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#214]
In general it would be good to move the versioning fields to the bottom of an element page, but above the comments.

Proposal for Study, Survey, Module 
[Page layout Survey, Study, Module.pdf](https://github.com/DASISH/qddt-client/files/585916/Page.layout.Survey.Study.Module.pdf)

Proposal for QuestionItem
[QuestionItem_pagelayout.pdf](https://github.com/DASISH/qddt-client/files/585998/QuestionItem_pagelayout.pdf)

This proposal is based on Stig's proposal in #206 and Yong's latest front-end development for missing values etc.

**Comment by liuy97** [comment]
The page layout of Question item is fixed at ##209.
