### ISSUE TITLE
Used_by: Improvement

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#220]
We have discussed an improvement for Used by:

![used_by1](https://cloud.githubusercontent.com/assets/20127077/20347488/b3f1f1dc-ac01-11e6-980d-3f53631692ae.PNG)
![used_by2](https://cloud.githubusercontent.com/assets/20127077/20347776/ccdde5ec-ac02-11e6-9091-916f75738bdf.PNG)

**Comment by BenjaminNSD** [comment]
We can wait working on this issue until the meeting thursday. 17.11.

**Comment by BenjaminNSD** [comment]
@liuy97 The new Used-by should be moved to buttom and replace the concept (above saving) as illustrated in the screenshot above. Maybe this was not quite clear in the issue?

**Comment by liuy97** [comment]
Please take a screenshot.

**Comment by BenjaminNSD** [comment]
![used_by2](https://cloud.githubusercontent.com/assets/20127077/20422572/8378d7f8-ad6b-11e6-99f2-563dff73713c.PNG)

**Comment by BenjaminNSD** [comment]
This is where used-by should be placed

**Comment by liuy97** [comment]
take a screenshot of what you saw.

**Comment by BenjaminNSD** [comment]
![used_by3](https://cloud.githubusercontent.com/assets/20127077/20422669/07b46e88-ad6c-11e6-9e4f-54ff78d4ccbd.PNG)

**Comment by liuy97** [comment]
You have to clear your browser history. This issue has been fixed.

**Comment by BenjaminNSD** [comment]
Great, it works in https://dasish.github.io/qddt-client

The screenshot was from https://qddt-test.nsd.no/

**Comment by liuy97** [comment]
Yes. That's site supposed to be updated every week. I can only keep the github page update.

**Comment by BenjaminNSD** [comment]
Sure. Thanks!
