### ISSUE TITLE
Add reference to based-on object to versioning details for versionable objects

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#221]
For QuestionItem and other versionable objects: Add  reference to based-on object in version details as displayed in the attachment
[Add based-on reference to version details.pdf](https://github.com/DASISH/qddt-client/files/596883/Add.based-on.reference.to.version.details.pdf)

**Comment by liuy97** [comment]
What's the content of the clickable basedon object? Is it similar to usedby?

**Comment by hildeorten** [comment]
@liuy97 In cases where an element is saved as a new element with a based-on reference to an existing element, it should be possible to view this 'based on' object by clicking on a link. The link should be available near the versioning details of the element, as for example in the pdf above. Could look similar to Used  by. 
PS: Not all elements have a based-on reference to a different object
