### ISSUE TITLE
Timestamp: include revision button not working

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#222]
I entered a new scale domain called "Sausage-Apple"

I saved 3 major versions and some as work in progress. In timestamp the revisions do not appear when clicking "include revisions"

**Comment by liuy97** [comment]
It looks like the backend only provides the revisions without WIP. You have to discuss it with Stig.

**Comment by StigNorland** [comment]
I made changes to the api, and notified @liuy97 
https://github.com/DASISH/qddt-client/issues/210

**Comment by liuy97** [comment]
The backend has filtered Revisions: work in progress (IN_DEVELOPMENT), UPDATED_HIERARCY_RELATION, UPDATED_PARENT.

Fixed at #224
