### ISSUE TITLE
Compare bug: wrong version displayed

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#223]
![compare_bug](https://cloud.githubusercontent.com/assets/20127077/20423004/0e892602-ad6e-11e6-8d02-053c99271d59.PNG)

see version number of compared item. it shows major 1 and minor 0 for both versions

**Comment by liuy97** [comment]
The major and minor is of the response domain. The information is correct.

**Comment by BenjaminNSD** [comment]
Ok. Once we can work a bit on the layout
