### ISSUE TITLE
QI: Bug: Name of ResponseDomain disappears

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#227]
When adding a missing domain to a question item, then the Name of the valid responsedomain disappears:

![qi_nameofrd](https://cloud.githubusercontent.com/assets/20127077/20554423/291e6b34-b15c-11e6-97c3-fcecb4da4997.PNG)

**Comment by liuy97** [comment]
@BenjaminNSD,
From the developer view, it's correct at the front end. The mixed domain is built on the category level (representation. That means that the information (such name, label) of the response domain which is a child of the mixed domain will be lost.

Why the name of the response domain is correct? The frontend has this information before submitted.

**Comment by BenjaminNSD** [comment]
I understand your perspective, but the user doesn't know what a mixedresponsedomain is. Would be good to have the name of the valid domain there. Can't you use the information from the table below?

![compare_bug2](https://cloud.githubusercontent.com/assets/20127077/20556586/26e32178-b168-11e6-9a52-0c0539ef0aac.PNG)

**Comment by BenjaminNSD** [comment]
I mean unders Response Domain should be the text "yes-no 11 oct" and under Missings "DON'T KNOW"

**Comment by liuy97** [comment]
I can parse the name of the mixed domain. The format of the mixed name should always keep the same. Otherwise, it will result in bugs if it changes.

**Comment by BenjaminNSD** [comment]
That's ok
