### ISSUE TITLE
Bug in versioning: QuestionConstruct and QuestionItem

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#231]
![qcbug](https://cloud.githubusercontent.com/assets/20127077/20624445/58298c30-b30d-11e6-95fb-2a7c1b6f6d18.PNG)

I have changed an instruction in a QC and saved first as meaning change and later as typo.

The version changed from 4.0 to 17.8

**Comment by StigNorland** [comment]
Can confirm bug!
Update function called 7 times, this is new behavior

**Comment by BenjaminNSD** [comment]
The bug is in  QuestionConstruct and QuestionItem!
