### ISSUE TITLE
QuestionConstruct: Bug in preview of instructions

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#233]
when changing instructions in QC the instructions disappear in preview after saving. When log out and and in again the preview is correct

**Comment by liuy97** [comment]
I confirm this bug. However, the backend returns empty instructions when changing it.

**Comment by BenjaminNSD** [comment]
@StigNorland assigned to Stig

**Comment by StigNorland** [comment]
it is working in my bakend,  will update test on monday....
