### ISSUE TITLE
Bug in preview if QuestionItem from concepts

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#237]
When I am in Concepts an click the magnifier on an attachedd QuestionItem, then the QuestionText is not dispkayed at the top of the preview. Instead, the responsedomain pops up

**Comment by liuy97** [comment]
QuestionText is displayed below name.

**Comment by BenjaminNSD** [comment]
Yes, It must be at the top. When you are in table questions and see the layout, there it's correct
