### ISSUE TITLE
QuestionConstruct: File upload not working

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#238]
Just testet to upload a file to an existing QuestionConstruct. After saving as new version no file is visible.

Don't know if this it is backend or fromtend error

**Comment by liuy97** [comment]
You have to click Button "upload".

**Comment by BenjaminNSD** [comment]
There is only File Upload or Link to uploaded file button. Upload not there in http://dasish.github.io/qddt-client

**Comment by liuy97** [comment]
click "file upload"
![screenshot from 2016-12-09 13-34-23](https://cloud.githubusercontent.com/assets/2961144/21049292/4d25b2d4-be14-11e6-8c67-04c01100185f.png)

**Comment by StigNorland** [comment]
I can confirm the error in download, however, the file is correctly stored at the server.

**Comment by StigNorland** [comment]
probably errors in the response header, treating it as text

**Comment by BenjaminNSD** [comment]
Det funker nå. Takk!

**Comment by BenjaminNSD** [comment]
Just Backend Exception error when I click on the uploaded file

**Comment by BenjaminNSD** [comment]
I
