### ISSUE TITLE
Bug in UsedBy: Info on usedby is incomplete

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#243]
The question “GVSLVOL” is used several times in different studies. Information is incomplete by multiple use in same study:

![usedby_error](https://cloud.githubusercontent.com/assets/20127077/21353150/14acd0d6-c6c5-11e6-8243-c4f3ef62db33.PNG)

Back- or frontend error?

**Comment by liuy97** [comment]
The backend does not provide the information you described. The following data is returned from the backend.
```
{
      "name" : "GVSLVOL",
      "id" : "7f000101-57bd-1b09-8157-d34cd9090016",
      "topicRef" : null
    }
```

**Comment by BenjaminNSD** [comment]
backen has implemented it. can test it after release today (21.12.)

**Comment by BenjaminNSD** [comment]
Error is still there. Check questionitem GVSLVOL
