### ISSUE TITLE
QuestionConstruct: Improve file upload

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#247]
Improvments to file upload:
1.	Remove upload button
2.	Chosen file will be uploaded when clicking on Submit-button (it triggers a new version of QC)
3.	Remove Link to uploaded file-button. Uploaded documents should always be displayed
4.	Add garbagebin-button to remove uploaded files

![fileupload](https://cloud.githubusercontent.com/assets/20127077/21355577/ccf43d4c-c6ce-11e6-9be3-84ec05315f7c.PNG)

**Comment by liuy97** [comment]
Point 1 and 2 are impossible for now. The backend has to support this mode firstly.

**Comment by StigNorland** [comment]
Upload button is good, otherwise I  agree.

**Comment by BenjaminNSD** [comment]
is it possible to use the open button as upload?

![fileupload2](https://cloud.githubusercontent.com/assets/20127077/21356111/c37031f2-c6d0-11e6-9c02-0bdc30af833e.PNG)

**Comment by BenjaminNSD** [comment]
It must not be possible to keep an uploaded file without saving the QC

**Comment by StigNorland** [comment]
Good question, I guess you can.

**Comment by liuy97** [comment]
Dialog button cannot be renamed, because it's os-dependent dialog.

When delete a file, the response from the backend has deleted it. But it is still there when refreshing pages.
