### ISSUE TITLE
Bug in QuestionConstruct: Update of QuestionItem version not correct

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#249]
When creating a new version of a construct, and using another version of the QuestionItem, the change will not be saved correctly.

After reload, the previous version of the QuestionItem appears.

**Comment by StigNorland** [comment]
see #246 
see wiki for explanation
https://github.com/DASISH/qddt-client/wiki/Early-bound

**Comment by liuy97** [comment]
I confirm that "questionItemRevision" is set correctly. The questionItemRevision response from the backend is also correctly. However, the questionItemRevision is incorrect after reloading.
