### ISSUE TITLE
QuestionConstruct: sort QuestinItem version descending

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#254]
The latest version should appear under QuestionItemVersion as default. When clicking on the arrow, the versions should appear in decending order
Sort QuestinItem version descending

![usethis1](https://cloud.githubusercontent.com/assets/20127077/21391274/459a0468-c78b-11e6-818e-0d08fb7decc5.PNG)

**Comment by liuy97** [comment]
Is the latest version is a business version?

If any version has been specified, does it still use the latest one?

**Comment by BenjaminNSD** [comment]
1. yes, only business versions can be viewed or selected by users
2. Good question! When you removed the question item first, and then choose a new one, the latest version should come up by default. When you click the edit button instead, the current version of QuestinItem should appear.
