### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#262]
Please check if it be possible for you to check the return codes and display the message that the server returns as Stig explains. See
![error message](https://cloud.githubusercontent.com/assets/10205366/21449808/3546ff32-c8f1-11e6-9985-d3c63a0cb6ca.PNG)
This should not take too much time for you, so please get back if this is a time consuming task

**Comment by liuy97** [comment]
I take one day off today. The reason is that the backend should return all data in **jSON format**. However, this oauth login api does not return JSON data. The return format is HTML.

**Comment by hildeorten** [comment]
I am very sorry for this. I then close this issue for now and wish you some good days off. See you on Tuesday 27th.
