### ISSUE TITLE
Comment added feature

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#263]
Comments have had a new property **isHidden** for a while.

When set to true, the comment and all children of said comment is not retrieved from server. 
(i.e. hidden) 

This functionality was made to facilitate a check out feature, when a comment no longer applies it is ok, to hide it. 

Add a Hide- check box or a delete button that sets flag (to true) and save comment immediately.

**Comment by liuy97** [comment]
isHidden is not hidden something, but not retrieved from the server. This property will exist for a while.

@hildeorten , @BenjaminNSD ,

Do you understand it?

**Comment by BenjaminNSD** [comment]
PLease use the trash bin button to delete comments
