### ISSUE TITLE
Bug Delete OtherMaterial (Files)

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#264]
Fileattachments (OtherMaterials) works in a slightly different maner than other entities in QDDT.

There isn't any contraints enforeced by the system or foreignkeys to abide. They are loosly assosiated to an entity, and need to be handled in a slighty different way.

To remove an OM from an entity you'll need to delete it manually using the /api/othermaterial/delete/{omId}
This will remove both the file and it's reference in the system all together.

**Comment by liuy97** [comment]
Then I suggest that OtherMaterials use same syntax with the others at the backend. Otherwise, you have to write a good documentation for it.

**Comment by liuy97** [comment]
The cause of this issue: When doing update, the OtherMaterials, which response from the backend, will show that the files have been deleted. However, the deleting file will still be there, when re-visiting it.

Fixed this issue at the frontend, let the other manage to delete files.
