### ISSUE TITLE
listing questionitems exception

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#266]
https://dasish.github.io/qddt-client/Questions

the backend will give the following message:
```JSON
{
  "id" : "null!",
  "url" : "http://qddt-test.nsd.no//questionitem/page",
  "exceptionMessage" : "Content must not be null!"
}
```
The frontend does not change accessing the api.

Did you change something at the backend?

**Comment by StigNorland** [comment]
no, I have seen this too. probably due to difference in database schema.

**Comment by StigNorland** [comment]
Error was in deployment, not code
