### ISSUE TITLE
Improve load time

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#272]
remove  these 2 calls from web-client, they are no longer needed.
**comment/page/by-owner/**   _(All comments are included when loading an entity)_
**concept/list/by-QuestionItem/** _(this is supplied by the entities themsleves)_

In Concept page there are alot of calls to 
**questionitem/page?&page=0**
please only call this when user press add-questions, as this query add a significant load to server and loading time for page.

**Comment by liuy97** [comment]
comments will be fixed at #248, close this.
