### ISSUE TITLE
Bug in saving in Question Item: Question text doesn't update 

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#274]
When saving an edited question item (question text was changed) as new or new based on, the question text does not change after refresh.

![sleep](https://cloud.githubusercontent.com/assets/20127077/21806894/41420ac6-d73c-11e6-8fa5-53e763947336.PNG)

**Comment by liuy97** [comment]
cannot reduplicate it.

**Comment by BenjaminNSD** [comment]
@liuy97 
Go to questions
Try to search Question Text "How do you sleep?"
Pick the first one (version 3.0).
Then change the question text to "How dou you sleep today?" and save as new Question.
Then refresh.
Then search sleep. 
Then you will see all questions having the same question text (bug)

**Comment by StigNorland** [comment]
This work in current version of web client

**Comment by StigNorland** [comment]
ahh I see, backend problem
question isn't copied over
