### ISSUE TITLE
Bug in saving in Domains: Saving as New or New based on doesn't work

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#275]
Tried to save a scale domain as  New or New based. When clicking the submit button, nothing happens. The button seems to be inactive.

**Comment by liuy97** [comment]
save as a new object, the backend responses en exception
```JOSN
{id: "statement", url: "http://qddt-test.nsd.no//responsedomain/",…}
exceptionMessage:"could not execute statement; SQL [n/a]; constraint [unq_responsedomain_name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
id:"statement"
url:"http://qddt-test.nsd.no//responsedomain/"
```

**Comment by StigNorland** [comment]
think this is sorted out... but please don't test more based on and new copy of... let me fix in backend first

**Comment by StigNorland** [comment]
Save as new is working correctly, but based on doesn't copy the underlying schema, which is very strange

**Comment by StigNorland** [comment]
based on and copy testet for
Responsedomain
QuestionItem
QuestionConstruct
Concept & Module should also work.
