### ISSUE TITLE
comments: increase N of characters

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#278]
a) Please increase number of characters in comments to 2000
b) make long comments readable (linebreak)

**Comment by liuy97** [comment]
Point a, it belongs to the backend.
Point b, It looks ok with linebreak. Please describe your idea in detail.

**Comment by BenjaminNSD** [comment]
![comment_length](https://cloud.githubusercontent.com/assets/20127077/21849693/620cac36-d807-11e6-80c9-d6f4b4542b23.PNG)

**Comment by BenjaminNSD** [comment]
Point b is shown in screenshot. Not entire comment is displayed

**Comment by BenjaminNSD** [comment]
![comment_long](https://cloud.githubusercontent.com/assets/20127077/21849849/329114be-d808-11e6-9719-651230bbc620.PNG)

comment should look like that after submit

**Comment by liuy97** [comment]
Ok. you have one very long word.

**Comment by BenjaminNSD** [comment]
Ahhh, the I close the issue, sorry
