### ISSUE TITLE
Bug in saving Question Items. error message

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#279]
I got two times the same error message when trying to create and save a new question item

![error_saving](https://cloud.githubusercontent.com/assets/20127077/21881670/8d750f76-d8a7-11e6-9502-6df0e0867d08.PNG)

**Comment by BenjaminNSD** [comment]
I presume the error results of a data entry error.

I edited a question item: I added a missing domain to a code domain and assigned a code to the missing category which already was used in the code domain.

we can change the error message in the future

**Comment by StigNorland** [comment]
this error is solved, created a new issue for error messages...
#414
