### ISSUE TITLE
add range setting in numeric domain

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#28]
Refs #24

support range from and to.

**Comment by StigNorland** [comment]
{"id":"378949ec-65d0-11e5-9d70-feff819cdc9f","modified":[2015,1,1,12,0,1],
"modifiedBy":{"id":"83d4c034-4ff9-11e5-885d-feff819cdc9f"},
"agency":{"id":"1359dede-9f18-11e5-8994-feff819cdc9f"},
"name":"VERY_BAD","basedOnObject":null,
"version":{"major":0,"minor":1,"versionLabel":null},
"changeKind":"CREATED",
"changeComment":null,
"code":null,
"children":[],"label":"Very bad","description":null,
**"inputLimit":{"minimum":"1","maximum":"1"},**
"classificationLevel":null,
"conceptReference":null,
"hierarchyLevel":"ENTITY",
"categoryType":"CATEGORY",
"links":[]}

**Comment by liuy97** [comment]
@StigNorland , @hildeorten ,

Does Numeric domain require a numeric category?

**Comment by hildeorten** [comment]
No category required for numeric domain

liuy97 skrev den 21.06.2016 13:25:
>
> @StigNorland <https://github.com/StigNorland> , @hildeorten
> <https://github.com/hildeorten> ,
>
> Does Numeric domain require a numeric category?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DASISH/qddt-client/issues/28#issuecomment-227412150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJu4tvq2A1Xea1eV3srlm_11ifslbGHdks5qN8ougaJpZM4Id7fC>.
>


-- 
Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no <http://nsd.no> | twitter.com/NSDdata <http://twitter.com/nsddata>

**Comment by liuy97** [comment]
@StigNorland , your implementation needs a numeric category. Is it correct?

**Comment by liuy97** [comment]
@StigNorland , @hildeorten ,

`Stig Norland: If you want a numeric responsedomain you need to attach a category with categoryType = NUMERIC`

Users have to specify to a category to a numeric response domain. This difference has to be mentioned to users.

**Comment by StigNorland** [comment]
yes, that is correct.

**Comment by hildeorten** [comment]
I would say this should not be called category in the tool as numeric
domain or representation is basically not a category in the meaning of
domain people nor in DDI. I would rather use the word 'representation'
for this

liuy97 skrev den 21.06.2016 13:48:

> @StigNorland https://github.com/StigNorland , @hildeorten
> https://github.com/hildeorten ,
> 
> |Stig Norland: If you want a numeric responsedomain you need to attach
> a category with categoryType = NjuMERIC NUMERIC|
> 
> Users have to specify to a category to a numeric response domain. This
> difference has to be mentioned to users.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/28#issuecomment-227416588,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tgfhUC__T79y_82MFn_kEVov4HX8ks5qN8-ggaJpZM4Id7fC.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by hildeorten** [comment]
I think it is better to use 'representation' (if this corresponds to
ManagedRepresentations in DDI) than CategoryType because CategoryType
means something different in DDI, please see
http://www.ddialliance.org/Specification/DDI-Lifecycle/3.1/XMLSchema/FieldLevelDocumentation/logicalproduct_xsd/complexTypes/CategoryType.html

It is very disadvantageous to let DDI names or domain names mean
something different in the tool

 liuy97 skrev den 21.06.2016 13:48:

> @StigNorland https://github.com/StigNorland , @hildeorten
> https://github.com/hildeorten ,
> 
> |Stig Norland: If you want a numeric responsedomain you need to attach
> a category with categoryType = NjuMERIC NUMERIC|
> 
> Users have to specify to a category to a numeric response domain. This
> difference has to be mentioned to users.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/28#issuecomment-227416588,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tgfhUC__T79y_82MFn_kEVov4HX8ks5qN8-ggaJpZM4Id7fC.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
ManagedRepresentations is ManagedRepresentations in tool and ddi

If anyone has a better name to describe these {CATEGORY NUMERIC TEXT DATETIME} then please let me know.
They all represent valid answers that are described/structured in ManagedRepresentations 

and given values when they implement a responsedomain.

**Comment by hildeorten** [comment]
Perhaps 'Response option type'?

Knut and Benjamin, what do you think?
Do you have some better ideas?

Good that ManagedRepresentations is the same in tool and DDI

 Stig Norland skrev den 21.06.2016 14:21:

> ManagedRepresentations is ManagedRepresentations in tool and ddi
> 
> If anyone has a better name to describe these {CATEGORY NUMERIC TEXT
> DATETIME} then please let me know.
> They all represent valid answers that are described/structured in
> ManagedRepresentations
> 
> and given values when they implement a responsedomain.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/28#issuecomment-227423096,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tvVuG4n9Psjm8a77Fn7MFj-E5x4bks5qN9dagaJpZM4Id7fC.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by hildeorten** [comment]
Keep it simple, maybe just "Response type"?

Hilde Orten skrev den 21.06.2016 14:27:

> Perhaps 'Response option type'?
> 
> Knut and Benjamin, what do you think?
> Do you have some better ideas?
> 
> Good that ManagedRepresentations is the same in tool and DDI
> 
>  Stig Norland skrev den 21.06.2016 14:21:
> 
> > ManagedRepresentations is ManagedRepresentations in tool and ddi
> > 
> > If anyone has a better name to describe these {CATEGORY NUMERIC TEXT 
> > DATETIME} then please let me know.
> > They all represent valid answers that are described/structured in 
> > ManagedRepresentations
> > 
> > and given values when they implement a responsedomain.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub 
> > https://github.com/DASISH/qddt-client/issues/28#issuecomment-227423096, 
> > or mute the thread 
> > https://github.com/notifications/unsubscribe/AJu4tvVuG4n9Psjm8a77Fn7MFj-E5x4bks5qN9dagaJpZM4Id7fC.
> 
> ## 
> 
> Hilde Orten
> Spesialrådgiver/Special Adviser
> Tel: +47 55 58 89 30
> nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

## 

Benjamin Beuster
seniorrådgiver/senior adviser
Tel: +47 55 58 89 15
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by hildeorten** [comment]
Sounds ok to me

Benjamin Beuster skrev den 21.06.2016 14:43:

> Keep it simple, maybe just "Response type"?
> 
> Hilde Orten skrev den 21.06.2016 14:27:
> 
> > Perhaps 'Response option type'?
> > 
> > Knut and Benjamin, what do you think?
> > Do you have some better ideas?
> > 
> > Good that ManagedRepresentations is the same in tool and DDI
> > 
> >  Stig Norland skrev den 21.06.2016 14:21:
> > 
> > > ManagedRepresentations is ManagedRepresentations in tool and ddi
> > > 
> > > If anyone has a better name to describe these {CATEGORY NUMERIC TEXT
> > > DATETIME} then please let me know.
> > > They all represent valid answers that are described/structured in
> > > ManagedRepresentations
> > > 
> > > and given values when they implement a responsedomain.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/DASISH/qddt-client/issues/28#issuecomment-227423096,
> > > or mute the thread
> > > https://github.com/notifications/unsubscribe/AJu4tvVuG4n9Psjm8a77Fn7MFj-E5x4bks5qN9dagaJpZM4Id7fC.
> > 
> > ## 
> > 
> > Hilde Orten
> > Spesialrådgiver/Special Adviser
> > Tel: +47 55 58 89 30
> > nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata
> 
> ## 
> 
> Benjamin Beuster
> seniorrådgiver/senior adviser
> Tel: +47 55 58 89 15
> nsd.no http://nsd.no |  twitter.com/NSDdata http://twitter.com/nsddata

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by liuy97** [comment]
It has to be noticed that datetime domain and text domain will have a same workflow as numeric workflow. A related category must exist before creating these domains.

**Comment by hildeorten** [comment]
Would it be possible to call this 'key' (refering to a controlled
vocabulary) rather than 'category'?

To call this category is confusing and should not be used, as this is no
category in terms of current domain practices and in DDI

liuy97 skrev den 22.06.2016 08:33:

> It has to be noticed that datetime domain and text domain will have a
> same workflow as numeric workflow. A related category must exist
> before creating these domains.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/28#issuecomment-227655805,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tkpV9qhTL_q1BoU1m1bwUvSX_9bnks5qONdJgaJpZM4Id7fC.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by liuy97** [comment]
@hildeorten ,

This described workflow depends on the backend. The backend needs a category there. But users will not need/understand it from my point of view.  That's why I describe the whole workflow here.

**Comment by kksnsd** [comment]
We publish what we have asap. It is extremely important that we do that now, and the most important thing is that scales and code lists work. Then we continue with the work on the response domins for the next version to be published.

**Comment by StigNorland** [comment]
It is the ManagedRepresentations  that defines what responsedomain we get. The responsedomain in it self is fairly agnostic to what it contains.
If the ManagedRepresentations  point to a "Category/Response type".DateTime, it is a datetime domain, same with Text and Numeric.
Everything else is either LIST/SCALE or MIXED.
