### ISSUE TITLE
Bug in QuestionItem: Wrong QuestionText saved

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#284]
I have created 3 different question (related with based on references). Somehow, the question text of one question is used for the other two. See example:

![qtext_error](https://cloud.githubusercontent.com/assets/20127077/21891319/63bcee12-d8d2-11e6-9f40-991a9700bd23.PNG)

**Comment by BenjaminNSD** [comment]
When I change the first one to "Muslims", the text of all Question changes

**Comment by StigNorland** [comment]
this is due to save as new bug.... (it is fixed, but these elements share question)
