### ISSUE TITLE
Bug in saving updated Responsdomain in QuestionItem(QI)

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#285]
When a new responsedomain has been selected or modified within a QI it is important to remove the current **responseDomainRevision** value, if you don't, the QI will point to the old version of it's RD not the one you just made or selected.
After saving a RD , set the QI.responseDomainRevision value to 0, the backend will find the latest version of the RD selected.

**Comment by liuy97** [comment]
Fixed at #252
