### ISSUE TITLE
Savin question items with mixed domain: RD name changes to Mixed[

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#294]
When editing a question and adding a valid domain and a missing domain, the name of the valid domain is changed to "Mixed ["

![mixeddomain](https://cloud.githubusercontent.com/assets/20127077/22057150/b122d10e-dd63-11e6-80e8-b30ea0fbedc5.PNG)

In earlier versions, correct name was displayed.

**Comment by liuy97** [comment]
see #227. I mentioned there. You said "ok".

**Comment by BenjaminNSD** [comment]
Maybe a misunderstand. Look at question item name "Smoking 3". There it is correct:

![mixeddomain2](https://cloud.githubusercontent.com/assets/20127077/22057435/efa1cde4-dd64-11e6-94d7-38d189b1a5d4.PNG)

in table it's also correct
![mixeddomain3](https://cloud.githubusercontent.com/assets/20127077/22057471/17457a6c-dd65-11e6-8e64-0c4ec1a29c25.PNG)

**Comment by liuy97** [comment]
See the highlight name. The format is different from the example you gave.

![screenshot from 2017-01-18 10-09-38](https://cloud.githubusercontent.com/assets/2961144/22057730/4ab91ede-dd66-11e6-9f8f-b8cae466f73a.png)

**Comment by liuy97** [comment]
![screenshot from 2017-01-18 10-13-20](https://cloud.githubusercontent.com/assets/2961144/22057840/c84956b6-dd66-11e6-9a41-013acf7b0d31.png)

**Comment by hildeorten** [comment]
Benjamin writes: Then it looks like a backend error @StigNorland

**Comment by BenjaminNSD** [comment]
Before saveing the question items, thevalid and missing responsedomain name is correct. after saving it becomes "Mixed ["

![mixeddomain4](https://cloud.githubusercontent.com/assets/20127077/22059144/f4731e3e-dd6b-11e6-8122-39fb5f383201.PNG)

**Comment by BenjaminNSD** [comment]
after saving:

![mixeddomain5](https://cloud.githubusercontent.com/assets/20127077/22059252/568210f8-dd6c-11e6-9e0c-6be1ae650d43.PNG)

**Comment by StigNorland** [comment]
The backend gives a mixed repsonsedomain a name in the format:
"Mixed [ {first RD name} + {last RD name} ]"

**Comment by StigNorland** [comment]
@liuy97 
![skjermbilde 2017-01-31 14 10 41](https://cloud.githubusercontent.com/assets/3939393/22466128/2545536c-e7bf-11e6-8c2d-95dfe61fc62c.png)

![skjermbilde 2017-01-31 14 07 47](https://cloud.githubusercontent.com/assets/3939393/22466072/e2141a7e-e7be-11e6-9c7e-18dcc697ad7c.png)

**Comment by StigNorland** [comment]
Also version is propagated to the managed representation as well
![skjermbilde 2017-01-31 14 12 34](https://cloud.githubusercontent.com/assets/3939393/22466196/7d25a29e-e7bf-11e6-8b4e-06e1761c37bd.png)
