### ISSUE TITLE
codes of a code domain can be alphanumeric

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#30]
The input from @hildeorten :

It is only for scale domain that the direction is important (see issue #29 ). In a code domain codes can also be alphanumeric like '**NO**','**SE**'. A code list also supports alphanumeric.

Codelist:
'**NO**' Norway
'**SE**' Sweden

**Comment by StigNorland** [comment]
That is not a problem, the codes are stored as strings anyway.

**Comment by liuy97** [comment]
Yes, you support it at the backend. However, the front end has to support this case.

**Comment by liuy97** [comment]
implemented.
