### ISSUE TITLE
Deleting of concepts not working

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#318]
Can't delete concepts at the moment

**Comment by StigNorland** [comment]
har testet med enkle concept, concept med under concept, concept med spørsmål og cocnept med under concept med spørsmål, ingen problemer. Kan du vise hva du prøver å slette?

**Comment by BenjaminNSD** [comment]
![sub1](https://cloud.githubusercontent.com/assets/20127077/22238604/a7ba00d4-e212-11e6-8c7f-effa3b9359c7.PNG)
![sub2](https://cloud.githubusercontent.com/assets/20127077/22238609/abfd80f8-e212-11e6-9711-cae32e48f695.PNG)

**Comment by BenjaminNSD** [comment]
@StigNorland see example below. Last Friday it didn't work eiher when I presented it live vie adobe connect.

![sub1](https://cloud.githubusercontent.com/assets/20127077/22238652/f16ba930-e212-11e6-88b4-b6b2bf701335.PNG)
![sub2](https://cloud.githubusercontent.com/assets/20127077/22238657/f7dcd5d2-e212-11e6-887c-0e35bc098ea0.PNG)
![sub3](https://cloud.githubusercontent.com/assets/20127077/22238749/6f46a224-e213-11e6-8a51-55b1a749d6b2.PNG)
