### ISSUE TITLE
Bug in Question Construct, preview

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#321]
See description below:
![cqb1](https://cloud.githubusercontent.com/assets/20127077/22240525/e786c496-e21b-11e6-9639-3b93cdff180c.PNG)
![cqb2](https://cloud.githubusercontent.com/assets/20127077/22240530/ea8425b2-e21b-11e6-8080-9686fee1c606.PNG)
![cqb3](https://cloud.githubusercontent.com/assets/20127077/22240535/ecf37c8a-e21b-11e6-8448-0c6e43fe8e48.PNG)

**Comment by liuy97** [comment]
It looks correct. Only business revisions will appear for options. When I saved the latest version as a business version, it will appear.

**Comment by BenjaminNSD** [comment]
You're right.

It's working correctly. Virginia and me were just confused because when you click on edit response domain, you see two response domain in preview. Above you see the response domain you edit, and below the current one attached to the questionconstruct.

This is all correct and in line with our specifications. The confusion stops when you click on "use this".

I close the issue
