### ISSUE TITLE
Improve double click in left menu

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#322]
Example in questions:

1. When searching the term “television”, I see all question items containing “television” in the table (OK)
2. When clicking the detail button, I see teh detail (OK)
3. Then I want to go back to the table. By double-clicking questions, I get back to the table. But in the table the filter “television” is still active
4. By double click, the table should be set to default

This applies also to domains, missings etc

**Comment by liuy97** [comment]
what's the default?

**Comment by BenjaminNSD** [comment]
Default: When you refresh, log in, and click on questions:
![cqb4](https://cloud.githubusercontent.com/assets/20127077/22242721/b714c5fc-e224-11e6-9b1b-e1a42eacdfd9.PNG)

**Comment by BenjaminNSD** [comment]
Table without filter
