### ISSUE TITLE
Timestamp compare, improvement

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#323]
In compare result, long text is displayed in one line. Is it possible to insert line breaks?

See example. The difference in the question text is only visible when scrolling to the right.

![compare_imp](https://cloud.githubusercontent.com/assets/20127077/22241425/8c500a8e-e21f-11e6-909f-9ac07ed1e0d5.PNG)

**Comment by liuy97** [comment]
I will suggest not to do so. It's difficult to control the layout.

**Comment by BenjaminNSD** [comment]
Ok, we postpone that. Not highest priority I change the milestone. Thanks

**Comment by StigNorland** [comment]
just use the horizontal scrollbar
