### ISSUE TITLE
Bug in scaledomain: Preview of anchors in table

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#327]
When I change the categories of the anchor points, they are not displayed in preview. It works after refresh.

![sclae_bug](https://cloud.githubusercontent.com/assets/20127077/22457274/0edebd20-e797-11e6-95d7-4abb1029740a.PNG)
![sclae_bug2](https://cloud.githubusercontent.com/assets/20127077/22457276/11a0a0c8-e797-11e6-9970-7b6975e502c3.PNG)

**Comment by liuy97** [comment]
Request URL:https://qddt-test.nsd.no/api/questionitem
Request Method:POST
Question: "Testquestion 22222?"

![poestrequest](https://cloud.githubusercontent.com/assets/2961144/22469936/ef95dd40-e7cd-11e6-97b2-cadc13fc28c9.png)

Reponse from the backend. Two IDs of the children are different from the request, which are same as the previous values. 
![reponse](https://cloud.githubusercontent.com/assets/2961144/22469946/f60bc8f6-e7cd-11e6-95f0-aeab4f9fbc3d.png)

**Comment by StigNorland** [comment]
Scaledomain will auto sort on codevalue, 
It will try to sort as number first and 
alphanumeric second ,
it is sorted ascending.
