### ISSUE TITLE
Bug in scaledomain: New categories stored without values

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#328]
When I edit an anchorpoint and type in a new category (red box), it's stored without the value I assignes to the category.

![sclae_bug3](https://cloud.githubusercontent.com/assets/20127077/22457473/f3a19ee6-e797-11e6-92f3-c743bda639bf.PNG)
![sclae_bug4](https://cloud.githubusercontent.com/assets/20127077/22457477/f647ead8-e797-11e6-8fc5-d1ce5824a0e6.PNG)

I guess it's a backend bug, but not wuite sure.

**Comment by liuy97** [comment]
confirmed that it's a bug at the front end.
