### ISSUE TITLE
no relationship between a study and its topics

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#33]
After a topic is created, request "topicgroup/list/by-study" cannot get any topics.

This bug is related to QDDT backend. I cannot create issues on QDDT, so create one here.

**Comment by StigNorland** [comment]
This should have been fix a few commits ago.

**Comment by liuy97** [comment]
This bug still occurs. After a question module is created, refresh the page and go to the UI of question module. A blank list will be there. There is no data in Table study_topic_groups.

**Comment by StigNorland** [comment]
This is working in the current commited code
