### ISSUE TITLE
Early binding of QuestionItem and Concept 

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#332]
Sarah writes:
“If I make a change to the text of a question item in the left hand menu, every occurrence of it in a module (i.e. where it is used by) automatically updates to the latest version”.

Short term solution (February): A concept will be bound to a specific version of a QuestionItem. If the QuestionItem is changed later on (new version), and the user wishes to use this new version, the link from Concept to QuestionItem  needs to be changed to point to this latest version.

Comment:  After February  goal: It should be possible to select which version of a concept that is used by a module, and which version of a concept a question item references. Style as in QuestionConstruct.

**Comment by StigNorland** [comment]
This feature will impact preformance, every question will be fetched manuanlly, and in topicgroups with lots of concepts and questions this will take time
