### ISSUE TITLE
Make both boxes the same height

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#334]
By adding a transparant image the same size as the add button (to the missing box) , both boxes would appear the same size. If there are better ways of solving this, please don't feel the need to follow my suggested solution
![skjermbilde 2017-02-01 10 58 54](https://cloud.githubusercontent.com/assets/3939393/22502546/9677901e-e86d-11e6-9622-991ffe4ee787.png)

**Comment by liuy97** [comment]
The height also is influenced by the string length. The lengths of the two strings are usually different.

**Comment by liuy97** [comment]
![screenshot from 2017-02-01 11-26-21](https://cloud.githubusercontent.com/assets/2961144/22503310/6eb3cdc8-e871-11e6-9949-f082c6eaf68c.png)
