### ISSUE TITLE
Timestamp compare: Improve constructs

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#336]
In construct, only label and description is compared.

We need:
Name, Pre instructions, Questin Text + version of question item, Post instructions, uploaded files

**Comment by liuy97** [comment]
@BenjaminNSD ,

How do you plan to compare Pre instructions, Post instructions, and uploaded files?

**Comment by BenjaminNSD** [comment]
To display the content as a string, example:

Name: A2 Alternative
Pre Instructions: Card 3
Question Text: On an average weekday, how much time, in total, do you spend watching television?
QI_Version: 2.0
Post instructions: GO TO A3
Files: QC_Text.PNG

**Comment by liuy97** [comment]
So everything is treated as string (files will only compare filenames), and then compare those strings.

**Comment by BenjaminNSD** [comment]
Yes
