### ISSUE TITLE
category/create with ID updates existing element

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#338]
When a new Category is used, the frontend correctly send this to the backend for saving.
However, if an ID is included the new Category will overwrite the existing element (with the same ID)
when creating new elements don't include IDs.

![skjermbilde 2017-02-01 15 00 14](https://cloud.githubusercontent.com/assets/3939393/22509640/3f205a72-e88f-11e6-9941-1f51f93ffec0.png)

This bug happens when updating a responsedomain with a new Category.

**Comment by StigNorland** [comment]
![skjermbilde 2017-02-01 15 05 06](https://cloud.githubusercontent.com/assets/3939393/22509820/e19a3f16-e88f-11e6-81cd-6044f8b92dc3.png)

**Comment by StigNorland** [comment]
I also found another error in saving which has confounded me a bit. Sometimes the code is missing after saving a responsedomain.
The reason is that Category doesn't contain the Code, it is attached to Category when it is part of a responsedomain.
The resullt is that the code is missing when it is returned for the server after saving it.
I am afraid you need to assign the code(s) to their Categoeries just before saving the repsonsedomain....
![skjermbilde 2017-02-01 15 08 01](https://cloud.githubusercontent.com/assets/3939393/22510048/c6134e3a-e890-11e6-80c8-692b9828b0c2.png)

**Comment by liuy97** [comment]
please write in detail how to reduplicate what you found.

**Comment by StigNorland** [comment]
1. Open an existing responsedomain
2. Change a category to a value that doesn't exists from before.
3. Save responsedomain.

**Comment by liuy97** [comment]
@StigNorland , please create a new issue for another problem.
