### ISSUE TITLE
lost code when saving responsedomain

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#339]
![skjermbilde 2017-02-01 15 08 01](https://cloud.githubusercontent.com/assets/3939393/22510879/f6867f3a-e893-11e6-89f4-ebe38ed2cd93.png)

error in saving which has confounded me a bit. Sometimes the code is missing after saving a responsedomain.
The reason is that Category doesn't contain the Code, it is attached to Category when it is part of a responsedomain.
The resullt is that the code is missing when it is returned for the server after saving it.
I am afraid you need to assign the code(s) to their Categoeries just before saving the repsonsedomain....

How to replicate

1.     Open an existing responsedomain
2.     Change a category to a value that doesn't exists from before.
3.     Save responsedomain.

**Comment by liuy97** [comment]
@StigNorland , wrote:
```
Open an existing responsedomain
Change a category to a value that doesn't exists from before.
Save responsedomain.
```
Change Response domain "Likelyhood4" the third category from 3 to 5. cannot reduplicate it.
Request
![screenshot from 2017-02-01 15-53-37](https://cloud.githubusercontent.com/assets/2961144/22511673/b032eaa2-e896-11e6-9c3f-a18ed377183b.png)

Response:
![screenshot from 2017-02-01 15-53-52](https://cloud.githubusercontent.com/assets/2961144/22511687/be6cc3a4-e896-11e6-8857-0cee9794fe91.png)

**Comment by StigNorland** [comment]
Not the code value, but the category.

**Comment by liuy97** [comment]
Test platform: https://dasish.github.io/qddt-client/Responsedomains
Test Response domain "Likelyhood4" 
![screenshot from 2017-02-02 09-01-12](https://cloud.githubusercontent.com/assets/2961144/22541446/89c8719e-e926-11e6-9ba5-f972ca5b8cad.png)
![screenshot from 2017-02-02 09-02-29](https://cloud.githubusercontent.com/assets/2961144/22541450/8cfab5c0-e926-11e6-9b31-1df05df0a5ba.png)

I cannot reduplicate it. Please write what you did step by step and reopen this.
