### ISSUE TITLE
exception when creating category template

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#34]
# Description:

After creating and editing category templates several times, this exception happens. But this error maybe does not occur immediately when the first category template is created.
# Requestion boday:

```
  categoryType:"LIST"
  children:[{id: "378949ec-65d0-11e5-9d70-feff819cdc9f", modified: [2015, 1, 1, 12, 0, 1],…}]  
  description:"sdf"
  label:"s3"
  name:"S3"
```
# Exception message:

Uncaught could not execute statement; SQL [n/a]; constraint [uk_98qo8cf5kyu4c5d0bcrd04cqg]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by StigNorland** [comment]
I will need more info, or a new commit so that I can test with your codebase, in order to replicate the error.

**Comment by liuy97** [comment]
Checkout the latest qddt-client code. Create one category schemes and modify it. Repeat these two steps a few times (maybe twice is enough) . The exception will happen.

`Uncaught could not execute statement; SQL [n/a]; constraint [uk_98qo8cf5kyu4c5d0bcrd04cqg]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

**Comment by StigNorland** [comment]
I made changes to the webpage, and to the server

**Comment by StigNorland** [comment]
Changes in relationship for category/child now makes it work, also added sort by column.
The way it is saved is the way it is opened.
