### ISSUE TITLE
Improve loading time for several list and pages

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#342]
When I work in concepts and go to questions in left menu, it takes some time until the questions come up in the table. It seems to be quite long taking into account that the amount of question still is small. In some surveys we can have several thousand questions.

Does the base handle that? Should we make a capacity test, import 1000 questions or something?

**Comment by StigNorland** [comment]
@liuy97 is working on #375, when he is finished with these changes I can update server with new lists and pages

**Comment by StigNorland** [comment]
My assumption that loading time was due to big json objects (they are big), was wrong. 
QuestionItem has several large query spaing large portions of the database .

**Comment by StigNorland** [comment]
issue with performance have been sloved (framework upgrade and and improvment in loading and datamodell)
