### ISSUE TITLE
Bug in timestamp compare: Question Construct

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#350]
Information from previous version is incomplete

![timespatmo_mis](https://cloud.githubusercontent.com/assets/20127077/22684375/5d071d6e-ed1c-11e6-813d-41fcbc4f5c60.PNG)

**Comment by liuy97** [comment]
The result is correct, because the backend returns an empty question item, given in the following image.

![screenshot from 2017-02-07 10-16-03](https://cloud.githubusercontent.com/assets/2961144/22684892/8904786a-ed1e-11e6-8c6a-de4cd0f4d4b8.png)

**Comment by BenjaminNSD** [comment]
Ok, so I assigned Stig to fix that
