### ISSUE TITLE
Deleting og Question Constructs not working

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#351]
![timespatmo_mis2](https://cloud.githubusercontent.com/assets/20127077/22684623/6af8cfde-ed1d-11e6-8baa-60e9d8d3ce51.PNG)

Don't know if it's backend or frontend error

**Comment by BenjaminNSD** [comment]
It's strange, some constructs can be deleted, others not.

For example, construct Name="A2 Alternative" question="On an average weekday, how much time, in total, do you spend watching television?" can't be deleted

**Comment by StigNorland** [comment]
found the bug,

**Comment by BenjaminNSD** [comment]
GREAT!!!
