### ISSUE TITLE
Error when making new question construct

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#357]
![bug_qc](https://cloud.githubusercontent.com/assets/20127077/22968190/c64fc0e8-f369-11e6-9e7b-6509190c10a1.PNG)

**Comment by StigNorland** [comment]
probably due to DB upgrade not finished

**Comment by StigNorland** [comment]
virker i qddt-test.nsd.no

**Comment by BenjaminNSD** [comment]
Now working also in/qddt-client
