### ISSUE TITLE
Split Category into two distinct pages

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#36]
On page to create different categories still to be named Category
And a new page where the "Template" creation is made (List/Range/Missing values)
Call this page Category Schema

and use Category list, Scale  & Missing Value as  names instead of List/Range/Missing values.

**Comment by liuy97** [comment]
@StigNorland , What's the meaning of "use Category list, Scale & Missing Value". When I create a "scale" scheme, I got exception:

`Uncaught Could not read document: Can not construct instance of no.nsd.qddt.domain.category.CategoryType from String value 'SCALE': value not one of declared Enum instance names: [DATETIME, TEXT, NUMERIC, CODE, MISSING_GROUP, LIST, RANGE, MIXED]`
