### ISSUE TITLE
In concept questionitem preview, wrong questionitem displayed

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#366]
After fixing backend bug, #362 

I discovered that preview of QuestionItem doesn't show correctly

How to replicate: create 2 concepts, attach QI to first concept.
edit said QI, and versioning it.
attach to second concept.

reload page, and check preview.

**Comment by liuy97** [comment]
Confirmed this bug after testing concepts again.

**Comment by hildeorten** [comment]
@liuy97 Hi, I tested to first add a question version (v3.1) to one concept, and then to edit the question to (v3.2). Then it updates in the concept to the latest version so not early binding (see #362). Is this a frontend or backend issue. Can you please check?

**Comment by hildeorten** [comment]
Hi,
I still get up the latest version of a QuestionItem in the concept, even if I saved it with a previous version.

**Comment by liuy97** [comment]
@hildeorten ,

That's right. Firstly, Concept does not support versioning. (if incorrect, please correct me). Secondly, what you reported is different from this issue (preview), please open a new issue.
