### ISSUE TITLE
Version history does not show for QuestionItem New_test

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#368]
Version history does not show for QuestionItem New_test, see below. Works for other items I tested though
![version history](https://cloud.githubusercontent.com/assets/10205366/23121456/c7ba90de-f760-11e6-8b8a-8fe40eaa998c.PNG)

**Comment by liuy97** [comment]
No version history returns from the back end.
![screenshot from 2017-02-20 11-47-42](https://cloud.githubusercontent.com/assets/2961144/23121889/7235767c-f762-11e6-87c3-33525fa8941c.png)

**Comment by hildeorten** [comment]
This is now taken forward in issue #371

**Comment by StigNorland** [comment]
This is due to changes in the concept / qi hierarchy. It might crash the
session. I have a fix for this...

**Comment by hildeorten** [comment]
Thank you Stig!
