### ISSUE TITLE
Exception ("Unable to get all revisions") when visiting "/category"

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#37]
`org.hibernate.exception.SQLGrammarException: could not extract ResultSet; nested exception is org.hibernate.envers.exception.AuditException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet`

Requested url  : "audit/category/<ID>/all"

**Comment by StigNorland** [comment]
This is due to manual insert into db (for test data), and that the revision system hasn't been invoked in this process. 
As far as I can tell it doesn't impact the system.
