### ISSUE TITLE
Name of mixed response domain

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#372]
The error was already reported earlier and fixed, but somehow it returned.

When making new questions with mixed domain, the name of the mixed domain is again wrong:
"category scheme for test - very likely - not at all likely" instead of "test - very likely - not at all likely"

Please remove "category scheme for ..." from name.

**Comment by liuy97** [comment]
Which one did you test?

**Comment by BenjaminNSD** [comment]
http://dasish.github.io/qddt-client

I made a new question:
name: test 999

You can see the error also at question BelRisk1 to BelRisk5 created 22. Feb 17

**Comment by liuy97** [comment]
The result I tested is that the name is produced by the backend.

![screenshot from 2017-03-06 09-55-39](https://cloud.githubusercontent.com/assets/2961144/23602933/1e77aa40-0253-11e7-860c-6a7821103487.png)

**Comment by BenjaminNSD** [comment]
I see, it's incorrect in the backend. 

I remember Stig said he can rename all rd-names in the backend, so I assign the issue to him

**Comment by StigNorland** [comment]
hackaton solution
after saving responsdomain, save managed representation one more time...
