### ISSUE TITLE
improve publication loadingtime

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#378]
When pressing details of a publication in publicationllist, fetch selected publication from server

**Comment by liuy97** [comment]
close this for now. The detail of the publication is not implemented yet.

**Comment by StigNorland** [comment]
This has to do with how you use the API.
pages and lists will have different (incomplete) information about elements, when you want to edit you'll need to load the complete element, not just summary.

**Comment by liuy97** [comment]
I see. But publication is still a demo.
