### ISSUE TITLE
How a response domain is specified code values for a category scheme?

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#38]
What's supposed to do at your api?

**Comment by liuy97** [comment]
Exception report: When creating a "LIST" response domain with two categories ("good" and "bad"), infinite loop happens between Category and code at the backend.

**Comment by StigNorland** [comment]
![skjermbilde 2016-06-09 12 42 04](https://cloud.githubusercontent.com/assets/3939393/15927095/de0aa12a-2e3f-11e6-9ffb-9251f9009597.png)

**Comment by StigNorland** [comment]
backend should now work, but the code assignement still do not work,
working on an improvement here....
