### ISSUE TITLE
Details for publication package content list

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#382]
Hi, see details in the attachment 
[Details for publication package content list.pdf](https://github.com/DASISH/qddt-client/files/827367/Details.for.publication.package.content.list.pdf)

**Comment by liuy97** [comment]
![screenshot from 2017-03-08 12-41-02](https://cloud.githubusercontent.com/assets/2961144/23702671/8c477d48-03fc-11e7-8680-300f8509420d.png)
