### ISSUE TITLE
Publication status vocabulary updates

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#384]
- The publication staus vocabulary should be updated according to the atteched list which includes proposal from City of 18th jan. to split the key PostPilot - SQP/TMT into two different keys (Pilot – SQP/TMT and Postpilot).

- The definitions should also be shown in the tool, see attchment.

[Publication status vocabulary updates.pdf](https://github.com/DASISH/qddt-client/files/831441/Publication.status.vocabulary.updates.pdf)

**Comment by liuy97** [comment]
![screenshot from 2017-03-14 11-44-04](https://cloud.githubusercontent.com/assets/2961144/23896941/91818fa2-08ab-11e7-9d63-2483c83c6ffd.png)
