### ISSUE TITLE
Can qddt-client support multiple usernames

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#39]
The current client shares one username (admin@example.org) to login. As a result, if a new visitor logins with it, the existing authentication will be invalidate. It's better to create one username for each user.

**Comment by StigNorland** [comment]
these user exist in the system today:
admin
user@example.org
yong
stig
review

**Comment by kksnsd** [comment]
How can I log in as "review", with access to the data created under user@example.org?

**Comment by StigNorland** [comment]
by using review@example.org ,same password

**Comment by StigNorland** [comment]
these users have been added to the system.
hilde.orten@nsd.no
knut.skjak@nsd.no
sarah.butt.1@city.ac.uk
lizzy.winstone.1@city.ac.uk
ess@city.ac.uk
benjamin.beuster@nsd.no
