### ISSUE TITLE
File download fix

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#390]
soluton found here [angular/issues](https://github.com/angular/angular/issues/14083)

changes in controlconstruct.service.ts
```
  getFile(id: string) {
    let headers = new Headers();
    let jwt = localStorage.getItem('jwt');
    if(jwt !== null) {
      headers.append('Authorization', 'Bearer  ' + JSON.parse(jwt).access_token);
    }
    let options = new RequestOptions({ headers: headers, responseType: ResponseContentType.Blob });
    return this.http.get(this.api + 'othermaterial/files/' + id,options)
                        .map(res => res.blob())
                        .catch(this.handleError)
  }

```

changes in controlconstruct.detail.componeent.ts

```
  onDownloadFile(o: any) {
    this.service.getFile(o.id).subscribe(blob => {
        fileSaver(blob,  o.originalName);
        if(blob._body.length !== o.size) {
          this.popupModal('The received size of the file is ' + blob._body.length
            + '. But the expected size is ' + o.size);
        }
      },
      error => this.popupModal(error));
  }
```

**Comment by StigNorland** [comment]
NB, I guess changes in controlconstruct.detail.componeent.ts aren't neccessary.

**Comment by liuy97** [comment]
Implement the modification, according the given description. It cannot be tested until uploading files are fixed. Close this for now. reopen it if any problem.

**Comment by StigNorland** [comment]
line 117 cause trouble in controlconstruct.detail.componeent.ts

 this.service.getFile(o.id).subscribe(data=> {
        fileSaver(data,  o.originalName);

**Comment by StigNorland** [comment]
(sorry about that...)

**Comment by liuy97** [comment]
Passed at Question construct "nnnn_test"
