### ISSUE TITLE
Publication status, detail preview for QuestionItem and QuestionConstruct when published 

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#396]
Please see attachment for details
[Publication status, detail preview for QuestionItem and QuestionConstruct when published_2.pdf](https://github.com/DASISH/qddt-client/files/855296/Publication.status.detail.preview.for.QuestionItem.and.QuestionConstruct.when.published_2.pdf)

**Comment by liuy97** [comment]
![screenshot from 2017-03-20 15-42-14](https://cloud.githubusercontent.com/assets/2961144/24104949/d38d64e8-0d83-11e7-9042-32f4726ec0a6.png)

@liuy97 Hi, here is one schreenshot where details regarding concept is explained
![pp questionitem detail](https://cloud.githubusercontent.com/assets/10205366/24139468/73423a2a-0e1c-11e7-8cf7-f46f5e6df1a1.PNG)

**Comment by liuy97** [comment]
![screenshot from 2017-03-20 15-42-49](https://cloud.githubusercontent.com/assets/2961144/24104995/ece93174-0d83-11e7-9514-b56e9bbe4588.png)

**Comment by StigNorland** [comment]
NB

I had to change publication/page and publication/page/search
They on longer returns  PublicationElement.elements

you can fetch them with the following api calls

/publication/{uuid}   [GET Publication] @PathVariable("id") UUID id
or
/publication/element/ [POST PublicationElement]  @RequestBody PublicationElement instance
returns PublicationElement with element
