### ISSUE TITLE
More users in qddt

### ISSUE THREAD

**Issue by kksnsd** [DASISH/qddt-client#40]
We need more user accounts in qddt as soon as the Resonse domains have been published

**Comment by StigNorland** [comment]
please provide names and emails to whom you want to add

**Comment by hildeorten** [comment]
Hi,

Please add Benjamin.Beuster@nsd.no as user

**Comment by StigNorland** [comment]
These emails have been added to the webpage:
hilde.orten@nsd.no
knut.skjak@nsd.no
sarah.butt.1@city.ac.uk
lizzy.winstone.1@city.ac.uk
ess@city.ac.uk
benjamin.beuster@nsd.no
