### ISSUE TITLE
Facilitate for Sequence type CV

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#403]
Hi,

Please facilitate for Sequence type CV. List should be as in the attachment
![sequence type cv](https://cloud.githubusercontent.com/assets/10205366/24198630/e5d7464e-0f06-11e7-8f65-e2dfa6573db7.PNG)

**Comment by StigNorland** [comment]
These values are what the backend expects in the field sequenceKind :
"Questionnare Sequence"
"Section Sequence"
"Battery Sequence"
"Universe Sequence"
