### ISSUE TITLE
ResponseDomain delete not implemented?

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#410]
after confirming a delete in Responsedomain, no command is sent to backend(?).

**Comment by liuy97** [comment]
Test: https://dasish.github.io/qddt-client/Responsedomains
delete: Trust scale (copy)
```
could not execute statement; SQL [n/a]; constraint [fk_dnhidu1wm2j1xmcbdw3c5fvc0]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```

**Comment by StigNorland** [comment]
can't delete elements in use...

**Comment by StigNorland** [comment]
I can make an userfriendly errormessage?

**Comment by liuy97** [comment]
So deleting the response domain works at the frontend. Close this for now. After you update your API for userfriendly messages, create a new issue.
