### ISSUE TITLE
Upgrade client Angular 4

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#411]
Angular 4 is released, and several library in use could also need upgrading.

Angular 4 has few breaking changes and is smaler and faster than Angular 2

**Comment by liuy97** [comment]
The critical dependence is still on Angular 2. 
https://github.com/InfomediaLtd/angular2-materialize/blob/master/package.json

Wait until that package upgrades.

**Comment by StigNorland** [comment]
I testet, no problem with materialize as far as I could see.
It took me about a minute....

**Comment by liuy97** [comment]
You can try yourself firstly. All of the UI is based on that package. Do you have tested all of the UI cases? It's safe to wait. I cannot see any good reason to take this risk with incompatible version.
