### ISSUE TITLE
Search and preview when adding QuestionConstruct to Sequence

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#413]
It should be possible to reference a particular version of a QuestionConstruct in Sequence.

The preview should look like when selecting Question Construct in Publication package: ![preview select question construct in sequence](https://cloud.githubusercontent.com/assets/10205366/24300083/899a4100-10ab-11e7-94b9-54729e419c32.PNG)

Search:
-It should be possible to search up QuestionConstruct to add by question construct name or question item name or question text.

-A text above the search field should be: 'Search for question construct name or question item name or question text'.

-Show search results like this: QuestionConstructNameIQuestionItemNameIQuestionText
Example: Belrisk1IBelrisk1I Using this card, how likely is it that you will be unemployed and looking for work for at least a month continually?

**Comment by StigNorland** [comment]
No, this we cannot add to the tool, it will have to be on the wish list for a new version.
However, you can make a copy of a specific version.

**Comment by BenjaminNSD** [comment]
So you can add a specific version of a question construct to a publication package, but only the latest one to a sequence?

**Comment by StigNorland** [comment]
This is an integrated feature of sequence...
