### ISSUE TITLE
Publication collapsable proposal

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#424]
Here is an example of how a hierarchical collapsable view could look and feel

![skjermbilde 2017-03-29 13 46 40](https://cloud.githubusercontent.com/assets/3939393/24612449/95a4a94a-1885-11e7-96e1-2b387cfa565d.png)

[collapsable.zip](https://github.com/DASISH/qddt-client/files/878883/collapsable.zip)

**Comment by BenjaminNSD** [comment]
Nice! How about the questions. Should they be included in the same way? How to distinguish between Concept and Question here?

**Comment by StigNorland** [comment]
Same as in concept view, a bullet point list.
I haven't included details or format, as I wanted to conway the concept of a collapsable hierarchical view.

**Comment by StigNorland** [comment]
For instanse, the "padding" left and right are just too wide in this example, and takes up too much real estate.

**Comment by BenjaminNSD** [comment]
Very nice, we just need to add the version number for each element on the right side for example.
In addition we need comments for each element

Can you make an example where the question is included. We can then assign the issue to Yong

**Comment by liuy97** [comment]
reduplicated at #437
