### ISSUE TITLE
Publication: External aid not displayed

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#425]
When adding a construct to a publication package, the external aid is not displayed

**Comment by BenjaminNSD** [comment]
See example: Publication package: april
element: question construct issue366.qc1

**Comment by liuy97** [comment]
No material information is received from the backend.
![screenshot from 2017-03-29 14-46-00](https://cloud.githubusercontent.com/assets/2961144/24455032/7a3307d8-148e-11e7-9c5d-364310600278.png)

**Comment by StigNorland** [comment]
None Audited entites, are not fetched by framework, even when using:

> If you want to audit a relation, where the target entity is not audited (that is the case for example with dictionary-like entities, which don't change and don't have to be audited), just annotate it with @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED). Then, when reading historic versions of your entity, the relation will always point to the "current" related entity.

**Comment by StigNorland** [comment]
This is  also an issue for comments....
#435
