### ISSUE TITLE
exception when creating a category scheme

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#43]
checkout the latest qddt and create  a category scheme (Type "List") with one category ("VERY_BAD") from demo.

Exception Message

``` json
{
  "id" : "statement",
  "url" : "http://nsd277.nsd.lan:8080/category/create/",
  "exceptionMessage" : "could not execute statement; SQL [n/a]; constraint [uk_98qo8cf5kyu4c5d0bcrd04cqg]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
```

**Comment by kksnsd** [comment]
Log in button is inactive

**Comment by liuy97** [comment]
@kksnsd , I visit qddt.nsd.no with IE10, FireFox 38 and Chrome 50, where Login button is active.

**Comment by StigNorland** [comment]
try starting a local version of the service and run client with "npm run dev"

**Comment by liuy97** [comment]
This bug has been fixed by Stig.
