### ISSUE TITLE
Change in rest API concept/page/by-topicgroup (questionItems are deprecated)

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#438]
In order for concept to hold versioned questionitem a change in the rest api has to be made.

A new node in the json have been made **conceptQuestionItems** which holds an array of objects:
```
{id{},
questionItem{},
updated{}
}
```
Read the questionItem from this structure instead of questionItems.

![skjermbilde 2017-04-18 09 45 29](https://cloud.githubusercontent.com/assets/3939393/25119887/3ddd2e9c-241c-11e7-9734-0e9fb67fd667.png)

**Comment by StigNorland** [comment]
It should be sufficient to add the ID (conceptId,questionItemId) to link concept + questionitem
![skjermbilde 2017-04-19 12 18 51](https://cloud.githubusercontent.com/assets/3939393/25175271/760f97ee-24fa-11e7-88ed-6384c911a37b.png)

**Comment by liuy97** [comment]
The response will return empty conceptQuestionItems.

Payload
![screenshot from 2017-04-20 10-29-26](https://cloud.githubusercontent.com/assets/2961144/25221121/44922078-25b4-11e7-89dd-0a5eda845f4e.png)

![screenshot from 2017-04-20 10-19-19](https://cloud.githubusercontent.com/assets/2961144/25221019/ecdc9700-25b3-11e7-9eb4-ca32bbde975e.png)

Response
![screenshot from 2017-04-20 10-19-46](https://cloud.githubusercontent.com/assets/2961144/25221061/117f2c1c-25b4-11e7-8601-d269e88336b8.png)

**Comment by BenjaminNSD** [comment]
I don't understand the issue, will this be solved by friday or should I remove the milestone for this issue?

**Comment by hildeorten** [comment]
Solved in backend, Yong, please continue
