### ISSUE TITLE
build errors with your commits of qddt-client on June 6

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#44]
please fix them. It's better that you can create an issue before you commit any code so that others can understand why you commit and when you finish committing. The issue number can be referred in your commit message.

**Comment by StigNorland** [comment]
can you be more specific? what fails?

**Comment by liuy97** [comment]
`src\components\questionitem\question_list.component.ts(3,32): error TS2307: Cannot find module './question_revision.component'.

src\components\questionitem\question_list.component.ts(5,9): error TS2305: Module '"qddt-client/src/components/questionitem/create.component"' has no exported member 'QuestionCreateCmp'.`

**Comment by StigNorland** [comment]
questionitem component removed, functionality  merged into question instead.
