### ISSUE TITLE
Publications: Display of question items within modules

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#446]
Layout of question item in popup is strange. The content fits not longer in the boxes

![quetsion_popup](https://cloud.githubusercontent.com/assets/20127077/25519011/762fe708-2bf6-11e7-9ff6-912853dbc253.PNG)

**Comment by StigNorland** [comment]
where is this from, can't find your example...

**Comment by BenjaminNSD** [comment]
When you open a publication package (for example "p5 (ok)") and then open the module "Welfare":
Concept: Beliefs --> Concept: Risk perception--> Question Items
