### ISSUE TITLE
Concept: Addition of QuestionItem should not lead to business version change in Concept

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#449]
Cullently an addition of a QuestionItem in Concept leads to a business version change. This should not be the case

**Comment by StigNorland** [comment]
@hildeorten when I add a QI to a Concept, business version doesn't change, however the Concept is saved
and status is set to UPDATED_HIERARCY_RELATION (it has a new revision but Version is the same).
This I cannot change, as the actually technial relationship has to be saved in the db.

**Comment by StigNorland** [comment]
What we can change is how this is interpreted by the model as a whole.
