### ISSUE TITLE
Concepts: Remove box of responsedomain in preview of published question items within concept tree

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#454]
The preview of quetion items within concepts and publications should be equal. Please remove box of responsedomain in preview of published question items within concept tree

![remove_responsedomain_2](https://cloud.githubusercontent.com/assets/20127077/25658951/b89b3d6e-3005-11e7-9f9e-3c3b446ee9f1.PNG)

**Comment by BenjaminNSD** [comment]
Attached questions to concepts within the menu "Home" stil have the response domain box. Please remove:
![concept_edit2](https://cloud.githubusercontent.com/assets/20127077/25695930/5baaa3a0-30b5-11e7-8cb7-4a4c3d48f7e6.PNG)

**Comment by liuy97** [comment]
Your image is related to the concept page, not publication context. What is the meaning of **published** in "preview of published question items"?

**Comment by liuy97** [comment]
Implemented as described.

**Comment by BenjaminNSD** [comment]
Great :+1:
