### ISSUE TITLE
Publications: Remove box of responsedomain in preview of  question items when selecting a question item

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#455]
In Publications: Remove box of responsedomain in preview of  question items when selecting a version of a question item for publishing
![remove_responsedomain_3](https://cloud.githubusercontent.com/assets/20127077/25659176/e235a9ba-3006-11e7-85ee-fe902c2e11f8.PNG)

**Comment by liuy97** [comment]
Fixed at #453
