### ISSUE TITLE
Include 'dismiss' button when selecting business versions

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#459]
It should be possible to dismiss an element in the select business version window, for use if the user discovers that a wrong element has been chosen. This applies in the following cases:
- When selecting a version of a response domain in a question item.
- When selecting a version of QuestionItem in QuestionConstruct
- When selecting business versions of elements for publication

See example below:
![dismiss button when selecting business version](https://cloud.githubusercontent.com/assets/10205366/25665479/009325c4-301e-11e7-85b0-374535e4cf55.PNG)

**Comment by BenjaminNSD** [comment]
Dismiss-button should have same size as Use this-button

**Comment by liuy97** [comment]
Does "dismiss" mean "close"?

**Comment by BenjaminNSD** [comment]
Dismiss means close or collapse
