### ISSUE TITLE
Universe element for QuestionConstruct

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#460]
A Universe element should be included for QuestionConstruct. Same functionality as Instructions.
Include Universe by reference in QuestionItem

Example for QC frontend:
![universe element](https://cloud.githubusercontent.com/assets/10205366/25666162/f8cb06b6-301f-11e7-8556-8e9858bba77f.PNG)

**Comment by BenjaminNSD** [comment]
Universe only available for existing QC, not for new QC
