### ISSUE TITLE
Reuse version of QuestionItem in concepts

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#462]
In concepts we need to select a version of a questionitem. Please use the template from publications as in example:

![reuse_qi_version](https://cloud.githubusercontent.com/assets/20127077/25736435/2167ce44-3172-11e7-80a8-0ee1af1a6cdc.PNG)

**Comment by BenjaminNSD** [comment]
A DISMISS-button should be added next to the USE THIS-button

**Comment by BenjaminNSD** [comment]
The backend still enters the latest version of the questionitem to the frontend

**Comment by StigNorland** [comment]
![bilde](https://cloud.githubusercontent.com/assets/3939393/25994358/dfe9f61c-370d-11e7-8537-e5bd830d882e.png)

**Comment by StigNorland** [comment]
![bilde](https://cloud.githubusercontent.com/assets/3939393/25994393/00278cdc-370e-11e7-88ee-1d1061d56f19.png)
Problem is that frontend doesn't supply a revision, and backend chooses the latest.
Add questionItemRevision to the new conceptQuestionItem and everything will be ok.

**Comment by StigNorland** [comment]
just a clearification, questionItemRevision  is not part of the ID, but should be a member of conceptQuestionItem

**Comment by BenjaminNSD** [comment]
Great you two solved that.
@liuy97 Is it possible to look at #476 since it's related
