### ISSUE TITLE
Publication: 1. Bug in preview of concepts when add items

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#466]
When selecting concepts, the attached question items are missing 

![concept_x2](https://cloud.githubusercontent.com/assets/20127077/25806225/d1ec5a86-3402-11e7-9365-5e2da50d8c4d.PNG)

It should contain these question items:
![concept_x1](https://cloud.githubusercontent.com/assets/20127077/25806240/ddfe58b0-3402-11e7-921c-eed6abb60e43.PNG)

**Comment by liuy97** [comment]
When you attached a question item, the change type is 
![screenshot from 2017-05-08 15-40-03](https://cloud.githubusercontent.com/assets/2961144/25806813/d1a9f932-3404-11e7-8b25-ad0dd7ca54e7.png)

When the business reversions are requested, they are ignored. (If any misunderstand, please comment here)
