### ISSUE TITLE
Publication: 2. Bug in preview of published concepts

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#467]
The attached question item is empty

![concept_x3](https://cloud.githubusercontent.com/assets/20127077/25806329/18a59cf8-3403-11e7-9cc6-92eea0499d7b.PNG)

should look like this:
![concept_x1](https://cloud.githubusercontent.com/assets/20127077/25806334/1ed858f4-3403-11e7-9418-28a79220dd02.PNG)

**Comment by liuy97** [comment]
@StigNorland ,
How to use your API? The element is empty.
publication: Test_package
![screenshot from 2017-05-08 15-35-22](https://cloud.githubusercontent.com/assets/2961144/25806614/11ab0bd0-3404-11e7-87ca-ae670cc0c34f.png)

**Comment by StigNorland** [comment]
backend

**Comment by StigNorland** [comment]
only QI left to populate...

**Comment by BenjaminNSD** [comment]
????

**Comment by BenjaminNSD** [comment]
We have to discuss approach with STig later
