### ISSUE TITLE
Print reports and PDF icons in the tool

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#468]
It should be possible to print the content and sub-content of each publication package in PDF. Include clickable Materialize ‘description’ icon on the right sidebar of the publication package page as shown in the image

For all elements survey, study, questionnaire module, concept, question item, response domain, category and question construct it should be possible to print reports that displays the development status of an element and its referenced content elements. Example for question construct below.
If the element itself, or any of the related sub elements have the revision label ‘in development’ or ‘hierarchy relation updated’ in the backend the report should list the status and details of these elements. 

 
![print development report](https://cloud.githubusercontent.com/assets/10205366/25852328/44f86184-34c9-11e7-83c7-56024aa3b525.PNG)
![print content report](https://cloud.githubusercontent.com/assets/10205366/25852327/44f89168-34c9-11e7-9991-c5742ccedd78.PNG)

**Comment by StigNorland** [comment]
I think http://materializecss.com/icons.html
"description" or "print" would work well

**Comment by BenjaminNSD** [comment]
I agree, but I would use description-icon for print development status and print-icon for print content report.

**Comment by StigNorland** [comment]
```
Publication/pdf/{id}

SurveyProgram/pdf/{id}
Study/pdf/{id}
TopicGroup/pdf/{id}
Concept/pdf/{id}

ControlConstruct/pdf/{id}
QuestionItem/pdf/{id}
```

**Comment by StigNorland** [comment]
PDF report is the active issue for this now, it has a reference to this issue
