### ISSUE TITLE
Concept QuestionItem select preview doesn't updates preview to current selected version

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#476]
![bilde](https://cloud.githubusercontent.com/assets/3939393/25994759/787c8af6-370f-11e7-86d7-c3e4a0c61f0c.png)

![bilde](https://cloud.githubusercontent.com/assets/3939393/25994777/8b329e88-370f-11e7-9f35-476122334a81.png)

**Comment by BenjaminNSD** [comment]
Assigned to our new frontent developer @StigNorland  ;-)
