### ISSUE TITLE
Moving up and down hierarchy 

### ISSUE THREAD

**Issue by sarah-city** [DASISH/qddt-client#48]
There is a "-" sign next to survey but not next to Study or Module

Is the idea of the "-" to let you move up a level in the same way that "+" moves you down a level?  Useful to have for Study or Module but not Survey which is the highest level

**Comment by StigNorland** [comment]
No, "-" was intended for deletion.
You can navigate between levels by selecting survey -> study -> topic in the top menu.

**Comment by StigNorland** [comment]
icons have been changed, this issue isn't relevant anymore.
