### ISSUE TITLE
Bug in QuestionItem when changing response domain II

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#481]
This applies when you edit a question.
When selecting a version of a response domain, you can select old version. When you click om USE THIS, the preview is empty.
The old response domain will be saved.
#480 

![imp1](https://cloud.githubusercontent.com/assets/20127077/26483749/f0f1a112-41ee-11e7-8319-1310ad41fb5c.PNG)
![imp2](https://cloud.githubusercontent.com/assets/20127077/26483752/f50e0812-41ee-11e7-91ae-96483633471e.PNG)

**Comment by StigNorland** [comment]
dialogbox stil lnot dismissed correctly
