### ISSUE TITLE
Number of elements referenced by a version may differ between element view and publication package view

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#493]
See example below. Solved for concept now according to Stig, but need to go through to see which elements this may apply for. Has to do with frontend error relating to addition and removal of elements probably, according to Stig.
![a111_2](https://user-images.githubusercontent.com/10205366/27277164-ad171efc-54dd-11e7-8464-353ced40be56.png)
![a111_1](https://user-images.githubusercontent.com/10205366/27277165-ad17bb0a-54dd-11e7-85f2-bbb4636f3a01.png)

**Comment by StigNorland** [comment]
Deletion of collection elements throughout this system, need to be verified, with regards to version history .

**Comment by StigNorland** [comment]
Bug was due to an errous way of removing QI from Concept which didn't updated the hierarchy correctly

**Comment by hildeorten** [comment]
Tested in QDDT test: When Question Constructs are published Instructions do not show. (Example N 88 in Test1Aug package)
