### ISSUE TITLE
Routing app issue

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#501]
This relates to City's issues 29 and 30 in their testiong document from July.

City writes:
29) after logging out only the left panel disappears but the main panel remains visible.
30) the   webpage for the QDDT doesn't always work properly. Apparently that has to do   with /home at the end of the link. This appears automatically when following   the qddt-link. But I needed to remove /home in order to access the tool,   otherwise it would give me an error code as in the screenshot.

**Comment by StigNorland** [comment]
Have been mimicking projectsetup in online examples, but that wasn't what was wrong.
suspect that it has to do with project metafiles (configuration of build scripts)
next week I will see if it is possible to merge qddt into a new project setup made for Angular4
