### ISSUE TITLE
Response cardinality, include checks

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#505]
This refers to issue 17 in City's testing feedback excel sheet from July.

City writes:

Response   cardinality fields accept any values, even if higher or lower than the number   of categories present in the domain.     Also, the minimum value can be higher than the maximum value.  

Add checks

**Comment by BenjaminNSD** [comment]
When increasing Response cardinality from 1 to 2 the style of the boxes changes in preview, from radiobutton to checkbox

**Comment by StigNorland** [comment]
and that is correct behavior for multi select.

**Comment by StigNorland** [comment]
scalre domain is fixed, lists not so much
