### ISSUE TITLE
Automatic saving of uploaded Other material/External aid

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#512]
This refers to City's issue 45 in the feedback from the testing excel sheet.

City writes: 
UI is   very unintuitive - the checkbox and green line that appear after selecting a   file make the user think the action has already happened, but the checkbox   actually needs to be clicked in order to upload the file!  Use same "Submit"/Dismiss icons   as used elsewhere

NB: This has low priority

**Comment by StigNorland** [comment]
I have redessigned this, now Other Material will save automatically together with normal save of element.
no files will be uploaded or deleted before a save is  done of its "parent" element
