### ISSUE TITLE
Submitting elements by pressing Enter

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#521]
This refers to issue 26 in City's feedback from the testing excel sheet.

City writes:
Hitting return key directly after entering the last code automatically results in submitting the code domain  This should be fixed as coud lead to errors - the user should have to press submit.

NB: This applies only when categories are created manually in code domain. Not when categories are reused

**Comment by BenjaminNSD** [comment]
This applies also to other elements like questions. When making a new question you can save the question by pressing Enter. I agree that the user should click Submit in order to save the new element
