### ISSUE TITLE
Add possibilities to select latest revision of Concept and QuestionItem 

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#526]
See attachment 
[Layout issue_select version.pdf](https://github.com/DASISH/qddt-client/files/1310240/Layout.issue_select.version.pdf)

**Comment by StigNorland** [comment]
QuestionItem is early bound and should not be selectable in other than whole version IMHO
Module should have the same option.
This only applies to publication? @hildeorten
