### ISSUE TITLE
Concept/question item issues

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#539]
This corresponds to issues 7 and 8 in Sarah's issues document of oct. 17. Should have priority for v2 of the tool

Sarah writes:
Removing a question item from a sub-concept appears to result in the entire sub-concept being deleted (though if you then leave and return to the page the sub-concept, minus quesiton item, is still there).  This is very confusing and needs to be fixed 

Sarah writes:
When I add a question item to a sub-concept this appears to result in the sub-concept being added as a new concept.  (though if you then leave and return to the page, the sub-concept only appears once as intended.  This is very confusing and needs to be fixed 

![bilde](https://user-images.githubusercontent.com/10205366/31721083-af0d7766-b418-11e7-91e2-ef39ba92cb6b.png)

**Comment by hildeorten** [comment]
When a question is removed from a concept the concept disappears but reappears after refresh, with a green(previous orange) inclamation mark

**Comment by StigNorland** [comment]
Similar problem with Module, also fixed
