### ISSUE TITLE
Add confirmation box to delete operations

### ISSUE THREAD

**Issue by sarah-city** [DASISH/qddt-client#54]
Possibly dangerous to have such an easy delete option next to questions 

At the same time it would be helpful to be able to delete concepts/questions  - and text within these - in case they mistakenly get entered in the wrong place.  It should be possible to undo genuine human error (spotted and corrected prior to a published version) without having to assign a rationale/new version

**Comment by StigNorland** [comment]
All the icons should be evaluated, and the delete function will have a confirmation dialog.

How a undo function should work, might need some discussion, before we implement it.

**Comment by StigNorland** [comment]
Add confirmation dialog when deleting elements (concepts)
Questions aren't deleted, so not necessary.
