### ISSUE TITLE
Wording change in warning for 'delete concept'

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#543]
This corresponds to issue 1 in Sarah's excel sheet of October 17th. This has priority 3 for v2 of the QDDT.

Sarah writes:
 Warning message that appears when try to delete a concept contains a typo.  Change "firstly" to "first".
![bilde](https://user-images.githubusercontent.com/10205366/31723024-060101aa-b41e-11e7-9ad8-fd0a56dbb206.png)

**Comment by StigNorland** [comment]
I also changed the wording 
_Are you sure to delete Concept_
to
_Are you sure you want to delete Concept_
