### ISSUE TITLE
History icon not working 

### ISSUE THREAD

**Issue by sarah-city** [DASISH/qddt-client#56]
The history icon - clock wrapped in an arrow - doesn't seem to be working.  Even where there are edits implemented it shows no info on history 

I tested it for concepts specifically

**Comment by StigNorland** [comment]
Yes, it is not working at one would expect. When you refresh the browser it will display correctly.

Don't think if we can make it to Mondays, release. but this will change before August.

**Comment by liuy97** [comment]
Refs #46, load history on demand and close this.
