### ISSUE TITLE
Versioning: error message

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#560]
When describing the change reason of an element and then pressing submit, I get a short error message "Description is mandatory" which disappears after some seconds

**Comment by StigNorland** [comment]
There are some issues with current version of Materialize that we use, related to 
https://github.com/DASISH/qddt-client/issues/521

**Comment by StigNorland** [comment]
Do you remember at which element you where in, when this happened. I gone through every page and couldn't replcatre this error (I have seen it myself, but don't remember where) @BenjaminNSD ?

**Comment by BenjaminNSD** [comment]
I just changed date time domain "Time test".

It occued again

**Comment by StigNorland** [comment]
There is an error here, it shouldn't save when form validation fails.
#568
