### ISSUE TITLE
problem of displaying revisions

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#59]
Firstly, a survey program is created. Its revision has a revision number (1) with Reason "created". When a study is created for this survey. The survey will have two revision numbers: (1) and (2), where both of the reasons are "created". But the revision number of the new created study will be (2).

(@hildeorten, please check whether this workflow is consistent with what you expect.)

**Comment by hildeorten** [comment]
Hi Yong,

Thanks, should I test this on your computer or on the published version?
If on your computer, will you please send me the link again?

Best wishes,

Hilde

liuy97 skrev den 13.06.2016 10:39:

> Firstly, a survey program is created. Its revision has a revision
> number (1) with Reason "created". When a study is created for this
> survey. The survey will have two revision numbers: (1) and (2), where
> both of the reasons are "created". But the revision number of the new
> created study will be (2).
> 
> (@hildeorten https://github.com/hildeorten, please check whether
> this workflow is consistent with what you expect.)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/59, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4thFD5YHyKbF8EGwB9Rbw92pgqnBzks5qLRc7gaJpZM4I0G06.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by hildeorten** [comment]
If the survey programme corresponds to the agency identifier, this will not be versioned, and thus not changed if a Study is created.

If the survey programme corresponds to a Group of Studies, this group will have a new business version when a Study is added. It would, however, not make sense to make business versions of a Group of Studies every time content of a Study under development is changed. Only the start of the development and the completion would make sense to make this business versions. Any save in between would represent a revision or a technical version.

A Study that is created for a Survey, for example corresponding to ‘ESS Round 1’, should have business version number 1.0 at its point of creation.  It makes sense to make business versions of Studies in connection with milestones in the instrument development, for example the starting point, the pilot, at the point of the final questionnaire etc.. Any save in between would be a revision or a technical version.

It can be confusing to use controlled vocabularies to document revisions and the business versions. These should be reserved for the business versioning, and should not be inherited upwards in the system

**Comment by liuy97** [comment]
Another problem here is how to count revision number. In Stig's implementation, the revisions of all the elements will share a revision system. As a result, the revision number of one element is not continuous.

**Comment by StigNorland** [comment]
Revisions are the systems own track of changes, and they work as intended.
If they are confusing, I can offer to hide them from view.
