### ISSUE TITLE
Green ! mark for high level 'based on' concepts does not appear when deleting sub-concepts

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#600]
Issue 4 in Sarah's testing feedback sheet of 010318:

The   green ! function does not work with “based on” concepts.  Deleting a lower order concept does not   trigger a green ! for the higher order concept in the same way it would for   new concepts

Priority 1 issue for the deliverable

**Comment by StigNorland** [comment]
was removed with purpose, however, disabling this, is no longer needed.
