### ISSUE TITLE
Delete: Instances where delete should not be possible

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#604]
Issue 8 in Sarah's testing feedback sheet of 010318:

You can currently delete a module if it   contains archived content.    This   should not be possible. It should also not be possible to delete a   QI/response domain if it is in use.

Priority 2 - fix for next release

**Comment by StigNorland** [comment]
prevention delete of Qi Responsedomain that are in use, will prevent you from only having a clean questionbase. (a question that was in your first study that is archived, shouldn't prevent you from deleting that question, it is simply not in usE any more.. it can stil lbe seen from the old study.
