### ISSUE TITLE
Memory of previoulsy entered text, disable for element description

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#605]
Issue 9 in Sarah's testing feedback sheet of 010318:

When   typing text into boxes (e.g. element descriptions) the qddt remembers   previously typed (and even subsequently deleted) text.    This is not helpful and should be   disabled.

**Comment by hildeorten** [comment]
Is this possible? Would this be useful in some instances?

**Comment by StigNorland** [comment]
browser functionality, cannot change
