### ISSUE TITLE
Code domain/Scale domain errors

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#609]
Issue 13 and 14 in Sarah's testing feedback sheet of 010318:

13: Theincrease/decrease arrows for number of codes, number of anchor points etc. do not work 

14: The   layout of the screen is misaligned
![bilde](https://user-images.githubusercontent.com/10205366/36899584-09cffa04-1e20-11e8-82a7-6dee3cf82337.png)

**Comment by StigNorland** [comment]
13 solved
