### ISSUE TITLE
Search box support

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#61]
@hildeorten 

Refs #60

What's described here is only for **demo** at the moment in order to understand the versioning workflow. Users will begin with a search interface. They can search with keywords on some Fields: label, description and elements related to the target, such as a response domain of a question item.

If any result is given, the users can choose **Reuse** it or create an element **based on business version**.
# Reuse

Term **Reuse** means the reference to this element. For example, Question item includes a response domain, which is "Reuse".
# Based on Business Version

This means that you create a new element based on an existing element at Business version (x.x, such as 1.0).
# Business version and Revision

QDDT has two different version concepts: business version and revision. All of changes will result in a revision. You can specify a revision to a business version. The business version is set to **1.0** when a new element is created.

**Comment by hildeorten** [comment]
Refs #60 https://github.com/DASISH/qddt-client/issues/60

The explanation of _Reuse_ and _Business version and Revision_ below is
fine.

Here is a comment to the term *Based on Business Version *as used below:
- ```
  A *Business version* is a particular revision of an object that
  ```
  
  is made part of the business versioning system. Some revisions are
  only intermediary development revisions and these are not part of
  the business versioning.
- -    New-based on\* is a different thing. Here the user decides to
    make a new object, but to be able to assign a based on reference to
    the existing object version.
    
    ```
      This is a decision made by the user because he/she thinks
    ```
    
    the object is now so different that it no longer can be viewed a a
    version of 'the same'.
  
  liuy97 skrev den 17.06.2016 12:04:
  
  > @hildeorten https://github.com/hildeorten
  > 
  > Refs #60 https://github.com/DASISH/qddt-client/issues/60
  > 
  > What's described here is only for _demo_ at the moment in order to
  > understand the versioning workflow. Users will begin with a search
  > interface. They can search with keywords on some Fields: label,
  > description and elements related to the target, such as a response
  > domain of a question item.
  > 
  > If any result is given, the users can choose _Reuse_ it or create an
  > element _based on business version_.
  > 
  >   Reuse
  > 
  > Term _Reuse_ means the reference to this element. For example,
  > Question item includes a response domain, which is "Reuse".
  > 
  >   Based on Business Version
  > 
  > This means that you create a new element based on an existing element
  > at Business version (x.x, such as 1.0).
  > 
  >   Business version and Revision
  > 
  > QDDT has two different version concepts: business version and
  > revision. All of changes will result in a revision. You can specify a
  > revision to a business version. The business version is set to _1.0_
  > when a new element is created.
  > 
  > —
  > You are receiving this because you were mentioned.
  > Reply to this email directly, view it on GitHub
  > https://github.com/DASISH/qddt-client/issues/61, or mute the thread
  > https://github.com/notifications/unsubscribe/AJu4tva6lBgq2jRtb1oI79wggljTh5N8ks5qMnEWgaJpZM4I4Nks.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
To keep consistency of behavior,  the system needs to bind to a revision. If some changes would not trigger a need for update and others would, the overall system would be more complex and unpredictable for the end user.
