### ISSUE TITLE
Turn off green mark?

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#615]
Sarah writes in testing feedback sheet 040318-2, issue 21:

Would be   helpful if user could decide a given change in hierarchy didn't warrant a   version change and so "turn off" the green ! triggered (having seen   and considered the warning).  A further   change in hierarchy could still trigger a new green !

Priority 3- nice to have

**Comment by StigNorland** [comment]
There will be some changes to how this is implemented, 
but at the level where we stop propagating a change (typical 1 level up) this status is needed.
