### ISSUE TITLE
Rational codes and comments when saving

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#62]
@hildeorten

Refs #60
# Rational Codes

Rational codes at Level 2 will be vertical. All of options will be visible.

Rational codes have to be given for each changes. However, only one comment is required for one save.
# Save options

Save options includes "**Save (Revision)**", "**Save as business version**" "**Save as a new Based on**" and "**Save as new**".
1. **Save (Revision)** will produce a new revision with the same id. Comment is **optional**.
2. **Save as business version** will get a new business version with the same id. Rational codes and Comment are required.
3. **Save as a new Based on** will get a new id based on this element. Comment is required.
4. **Save as new** will get a complete new element. No comment is needed.

**Comment by hildeorten** [comment]
Rationale Codes: OK

Save options:
Comment should in my view be optional. Will consult with the other
domain people and get back regarding this.

liuy97 skrev den 17.06.2016 12:50:

> @hildeorten https://github.com/hildeorten
> 
> Refs #60 https://github.com/DASISH/qddt-client/issues/60
> 
>   Rational Codes
> 
> Rational codes at Level 2 will be vertical. All of options will be
> visible.
> 
> Rational codes have to be given for each changes. However, only one
> comment is required for one save.
> 
>   Save options
> 
> Save options includes "_Save (Revision)_", "_Save as business
> version_" "_Save as a new Based on_" and "_Save as new_".
> 1. _Save (Revision)_ will produce a new revision with the same id.
>    Comment is mandatory.
> 2. _Save as business version_ will get a new business version with
>    the same id. Rational codes and Comment are required.
> 3. _Save as a new Based on_ will get a new id based on this element.
>    Comment is required.
> 4. _Save as new_ will get a complete new element. No comment is needed.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/62, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4ttGjrZRlGAxp0ir94bko5VNXTDCQks5qMnvYgaJpZM4I4Pqn.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
What is the intention of Save as  new without keeping it as based on (which it is)

**Comment by liuy97** [comment]
A new element is created. However, this element will drop all relationships with its based element.

**Comment by hildeorten** [comment]
When the changes made makes the element so different from the 'original'
that it does not make sense to have a based on reference to that element
any more

Stig Norland skrev den 24.06.2016 14:07:

> What is the intention of Save as new without keeping it as based on
> (which it is)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/62#issuecomment-228329179,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tk0HS3JAeL6rOCm_dPj14xfCURH-ks5qO8hsgaJpZM4I4Pqn.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by liuy97** [comment]
Fixed at #63
