### ISSUE TITLE
How can i login this application no any credentials?

### ISSUE THREAD

**Issue by yogesh-sonar** [DASISH/qddt-client#624]
How can I log in this application no any credentials? you have to mention.
plz, help me with that issue.
thanks in advance

**Comment by StigNorland** [comment]
You will also need the backend 
https://github.com/DASISH/qddt-server
I have setup docker to run postgres, but any DB will work.

**Comment by yogesh-sonar** [comment]
But now I cant do it that way I'm saying you help me.
and you shared link is going to 404 so plz check it asap

**Comment by StigNorland** [comment]
sorry 
https://github.com/DASISH/qddt-service
