### ISSUE TITLE
Code domain: Save of new dissappears after refresh

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#628]
I can save a code domain, but it disappears after referesh. Maybe this applies to more domains

**Comment by hildeorten** [comment]
I tried to edit the code domain before refresh by adding more codes. I was not permitted to save

**Comment by StigNorland** [comment]
missing commit from home.... (is working)

**Comment by hildeorten** [comment]
Great thanks!

Fra: Stig Norland [mailto:notifications@github.com]
Sendt: 23. april 2018 16:17
Til: DASISH/qddt-client
Kopi: Hilde Orten; Author
Emne: Re: [DASISH/qddt-client] Code domain: Save of new dissappears after refresh (#628)


missing commit from home.... (is working)
