### ISSUE TITLE
Change metadata for saving

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#63]
@hildeorten

Refs #60

Some additional information may be useful, which is listed as follows.

| Field | Description |
| --- | --- |
| Change Name | which item has been changed, such as **label** or **description**. |
| Change Type | Addition, Removal and Change |
| Rational L1 | TypeOrNoMeaningChange or MeaningChange |
| Rational L2 | Real life change, more see Refs #60. |

The above information will be saved if possible. The change of **Name** and **Type** will be detect by machine. Rational L1 and L2 should be selected by the user (userdefined). However, users will make a final decision.

@liuy97 October 19: For now we will not implement the Change Name option described above

**Comment by hildeorten** [comment]
Great but Rational L1 and L2 should be selected by the user (userdefined)

 liuy97 skrev den 17.06.2016 13:02:

> @hildeorten https://github.com/hildeorten
> 
> Refs #60 https://github.com/DASISH/qddt-client/issues/60
> 
> Some additional information may be useful, which is listed as follows.
> 
> Field     Description
> Change Name   which item has been changed, such as _label_ or
> _description_.
> Change Type   Addition, Removal and Change
> Rational L1   TypeOrNoMeaningChange or MeaningChange
> Rational L2   Real life change, more see Refs #60
> https://github.com/DASISH/qddt-client/issues/60.
> 
> The above information will be saved if possible. The change will be
> detect by machine. However, users will make a final decision.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/63, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4thmW-KovWa63M4zPlnILHie2nSeUks5qMn6sgaJpZM4I4QL3.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
change name and change type is handled by the system without any intervention by humans.

**Comment by StigNorland** [comment]
Rational code L1 and L2 is now flattened (to a list)
if you think the user experience is better with a hierarchical "view" we could display the different items in a list with indents, suggesting a hierarchy, but still all visible to the end user.

**Comment by hildeorten** [comment]
Yes would be good as we fear that ortographical and the other version
rationales can be perceived as overlapping if it is not possible to
relate to a hirearchy where 'typo or no meaning change' and 'meaning
change' is not involved aswell

Stig Norland skrev den 17.06.2016 15:43:

> Rational code L1 and L2 is now flattened (to a list)
> if you think the user experience is better with a hierarchical "view"
> we could display the different items in a list with indents,
> suggesting a hierarchy, but still all visible to the end user.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/63#issuecomment-226772086,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tr0wBrHBB4q_dWqGCkIRLATQ4E4yks5qMqSUgaJpZM4I4QL3.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by BenjaminNSD** [comment]
@StigNorland

To finalise the versioning system:

Please find the following attached:
- A list of Vertioning rationale codes with terms and definitions
  [Save type5.docx](https://github.com/DASISH/qddt-client/files/461523/Save.type5.docx)

**Comment by StigNorland** [comment]
```
    IN_DEVELOPMENT,
    TYPO,
    CONCEPTUAL,
    EXTERNAL,
    OTHER,
    ADDED_CONTENT,
    BASED_ON,
    TRANSLATED
```

These are the valid status from the backend. They are enums, and that limits what characters I can use in their names.

Suggest that you create a list in frontend with filters that will show/hide status according to user choices.

**Comment by hildeorten** [comment]
@liuy97 See attached pdf Savetype 6 for implementation
[Save.type6.pdf](https://github.com/DASISH/qddt-client/files/508277/Save.type6.pdf)

**Comment by liuy97** [comment]
ok

**Comment by liuy97** [comment]
@StigNorland,

Which field is used to store rational code?

Where is your qddt repository? I still use Dag's repository which is no update.

**Comment by BenjaminNSD** [comment]
Stig creates a mapping table!

**Comment by StigNorland** [comment]
`

```
IN_DEVELOPMENT
TYPO            TypoOrNoMeaningChange
CONCEPTUAL      MeaningChange.ConceptualImprovement

EXTERNAL        MeaningChange.RealLifeChange

ADDED_CONTENT   MeaningChange.AddContentElement

OTHER           MeaningChange.OtherPurpose

BASED_ON        CopyOfSource        NB -> this is not possible (an uuid is uniqe and cannot be "reused"

BASED_ON        VariantOfSource

TRANSLATED      TranslationOfSource
```

`

@liuy97 

This is a one to one map of status codes

**Comment by BenjaminNSD** [comment]
By Copy of source we mean a new element where the content is identical to that of
 an existing element but the ID is different

**Comment by liuy97** [comment]
@StigNorland ,

As you descrited, do you use the field of "change types" for both "change types" and "rational codes"? I have to parse them when I read it.

**Comment by liuy97** [comment]
@StigNorland ,

Did you commit your related code? I found that you did not commit your code today.
