### ISSUE TITLE
create a question item UI for concepts

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#64]
Search question items if have any, and use the latest version. Otherwise, create a new question item with a question and response domain.

**Comment by StigNorland** [comment]
QuestionItem first implementation just show as everything else (ignore versions)
modify question service to query against questionitem, not question
modify view to have an extra level (QI) that wraps question.
https://github.com/DASISH/qddt-client/wiki/QuestionItem

**Comment by liuy97** [comment]
`POST /questionitem/create
BODY {"question":{"name":"q1","question":"q1","intent":"q1"},"responseDomain":{}}`
`Uncaught org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing`

**Comment by liuy97** [comment]
@hildeorten 

I just describe for you how the workflow of question item works at the current status.
When attaching a question item, users will search question text and response domains. Attaching will trigger creating a question item. This question item will be never reused.

**Comment by liuy97** [comment]
@StigNorland 
How is a created question item attached to a concept?

**Comment by hildeorten** [comment]
The QuestionItem is the reusable core component of a survey questionnaire.

It will never be reused within the same study but often reused between
studies over time.
This is not possible in the db model of Stig but will be implemented for
the QVDB.

QuestionItem should have some additional components in addition to the
question text and the response domain reference:
Question  
    Name
    Description (Question intent)
    Question text
    Concept reference
    Response domain reference
    Response cardinality

For further information, please see p. 20-24 in Core Domain model
document document at
https://github.com/DASISH/survey-tools-metadata/tree/master/core-domain-model.

liuy97 skrev den 20.06.2016 11:51:

> @hildeorten https://github.com/hildeorten
> 
> I just describe for you how the workflow of question item works at the
> current status.
> When attaching a question item, users will search question text and
> response domains. Attaching will trigger creating a question item.
> This question item will be never reused.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/64#issuecomment-227098263,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tqh2AaM4LFAbQDWmNj5hvm2NA0gnks5qNmKOgaJpZM4I4Tbq.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata
