### ISSUE TITLE
update hapijs / hoek

### ISSUE THREAD

**Issue by borsna** [DASISH/qddt-client#641]
Got some email notifications from GitHub regaring this a few times. 
pasting it as an issue to make it visible:
```
Known moderate severity security vulnerability detected in 
hoek < 5.0.3 defined in package-lock.json.
--
package-lock.json update suggested: hoek ~> 5.0.3.
```
https://github.com/DASISH/qddt-client/network/dependencies

**Comment by StigNorland** [comment]
Thanks, hapijs is part of many sub libraries, including Angular 5.

As it is part of their dependencies, there aren't anytihng I can do about it. (besides waiting and updating when they have fixed their dependencies)

**Comment by borsna** [comment]
Ah, okay. I´m not familiar with the angular ecosystem. Good to know 👍

**Comment by StigNorland** [comment]
This is now fixed.
