### ISSUE TITLE
question items will be empty when creating a question item for concept

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#65]
Refs #64, 

After creating a question item, the relationship between question item and concept is not built. The problem is how to attach/detach question items to a concept.

**Comment by hildeorten** [comment]
In DDI the QuestionItem references the concept. Conceptually this is a
good way. See core domain model.

At the same time it would be useful to see the related question items
from the concept window.

liuy97 skrev den 20.06.2016 14:14:

> Refs #64 https://github.com/DASISH/qddt-client/issues/64,
> 
> After creating a question item, the relationship between question item
> and concept is not built. The problem is how to attach/detach question
> items to a concept.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/65, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4ts5cGj5phQ_B8TokmqCuL_YqV-rVks5qNoQMgaJpZM4I5o3x.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by liuy97** [comment]
to Knut,

This bug has to been fixed, otherwise, a question item will not be attached to a concept at all.

**Comment by StigNorland** [comment]
As long as Concept already is defined in DB, you can add a questionitem to its Concept.questionItems 
and persist Concept  again.

```
    QuestionItem questionItem = new QuestionItem();
    questionItem.setQuestion(question);

    Concept concept = new Concept();
    concept = conceptService.save(concept);

    concept.getQuestionItems().add(questionItem);
    conceptService.save(concept);
```
