### ISSUE TITLE
QuestionConstruct:  New text in ‘Universe’ or ‘Instruction’ is added by clicking ‘enter’. Clicking on the ‘add’ tab does not work

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#650]
New text in ‘Universe’ or ‘Instruction’ is added by clicking ‘enter’. 
Clicking on the ‘add’ tab does not work and an error message appears.
See picture below
![error message 2](https://user-images.githubusercontent.com/10205366/40612768-1e692ddc-627c-11e8-85dd-6f9922468319.png)

**Comment by StigNorland** [comment]
Greide  både å legge til ved trykke enter og ved å trykke "add"

Kan du skrive ned stegene du tar for å få feilen?

**Comment by StigNorland** [comment]
NB, om du lagrer formet, slik det ser ut på bildet ditt, har du ikke trykket add eller enter.
Om du tykker enter eller #add" forsvinner rammen rundt teksten, og det blir lagt til formet.

**Comment by hildeorten** [comment]
Ok, Takk. Det funket. Min feil

**Comment by StigNorland** [comment]
https://github.com/DASISH/qddt-client/wiki/Search-Selector-List

**Comment by hildeorten** [comment]
Fin ☺


Fra: Stig Norland [mailto:notifications@github.com]
Sendt: 29. mai 2018 10:51
Til: DASISH/qddt-client
Kopi: Hilde Orten; State change
Emne: Re: [DASISH/qddt-client] QuestionConstruct: New text in ‘Universe’ or ‘Instruction’ is added by clicking ‘enter’. Clicking on the ‘add’ tab does not work (#650)


https://github.com/DASISH/qddt-client/wiki/Search-Selector-List
