### ISSUE TITLE
Text format in elements

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#651]
Issue 22 (priority 3) and 23 (priority 2) from Sarah's testing sheet of 310718 

Sarah writes: 

22 Would be   nice if comments appeared as rich text

23 qi needs   to be rich text

**Comment by hildeorten** [comment]
We need to discuss which formats to use - should be generic and reusable as possible

**Comment by StigNorland** [comment]
Comments and all description fields in qddt now support html tags.
There is no editor

![image](https://user-images.githubusercontent.com/3939393/48805282-34c29c00-ed17-11e8-8645-13ec67784b7a.png)
