### ISSUE TITLE
Order of elements and Toc

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#653]
Issue 1a (priority 1) and 11 (priority 3) from Sarah's testing sheet of 310718

Sarah writes: 
1a Still not clear in what order concepts are displayed in ToC.  Can it be order originally entered rather than order last updated or alphabetical? 

11 When multiple Qis appear under the same concept, the order changes depending on which QI is added 2nd.   It would be better if the user could choose and fix the order 

Agreement to make this alphabetically first and improve later using drag and drop functionality

**Comment by StigNorland** [comment]
#746
