### ISSUE TITLE
response domain will get all of response domains

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#66]
request:
`/responsedomain/page/search?ResponseKind=SCALE`
`/responsedomain/page/search?ResponseKind=LIST`

All of response domains will be got.

**Comment by StigNorland** [comment]
```
DATETIME,
TEXT,
NUMERIC,
LIST,
SCALE,
MIXED
```

Are the vaild Responsekind available, and the tests works.

**Comment by StigNorland** [comment]
Description (responsedomain.description)
Question (question.text)
Name (responsedomain.name)
Are also valid params to this call

**Comment by liuy97** [comment]
The problem here is that all types of response domains will be returned when you request one type (such as numeric) of response domains.

**Comment by StigNorland** [comment]
That is very strange as 
these tests actually return what you would expect.
mvc.perform(get("/responsedomain/page/search?ResponseKind=LIST").
mvc.perform(get("/responsedomain/page/search?ResponseKind=SCALE")
mvc.perform(get("/responsedomain/page/search?ResponseKind=MIXED")

**Comment by liuy97** [comment]
Well, it depends on the quality of your tests. You unit tests are to test your java code, not rest api. It's better to use qddt-client to confirm it.

**Comment by StigNorland** [comment]
I can see that you are querying the api correctly.
what is very weird is that web and mvc mock doesn't behave the same way about optional parameters.
Found the error in my repository, now it works.
