### ISSUE TITLE
Question Item

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#674]
When   trying to repeat the procedure described at issue #675 for another item, I   received the error message in the attached screenshot and was not able to   attach the selected 'mixed' response domain.

**Comment by hildeorten** [comment]
This corresponds to issue 14 in QDDT post v1 feedback log from City

**Comment by loucasal** [comment]
![Issue #14](https://user-images.githubusercontent.com/25279797/59269010-e5f23a80-8c45-11e9-9318-3a47f3fa7c19.PNG)

**Comment by StigNorland** [comment]
This will not be fixed in the first release to production
