### ISSUE TITLE
QuestionItem

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#675]
When   adding a response domain to item 'Frequency digital social contact child   (chdsc) item 5', I was able to select the 'mixed' option including both a   response domain and missings at the same time (unlike for other items entered   earlier), however this 'mixed' response domain appears as 'not saved as a   version' (yellow exclamation mark symbol). Shouldn't that appear as saved as   version 1.0?

**Comment by hildeorten** [comment]
This corresponds to issue 13 in QDDT post v1 feedback log from City

**Comment by StigNorland** [comment]
I have seen this from time to time, but cannot reproduce this error
