### ISSUE TITLE
Grid in qddt

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#68]
We have need for a grid that will take a paging endpoint from qddt back end and transfer it to a 
sorting/paging/searching/inline editing grid on the front end.

It should be component based, so that it can be reused by several object collections.

This implementation has what we need, and it support Angular2 https://www.ag-grid.com/. There are several others to choose from. If it is possible to implement one from scratch in less than one week, we could make it ourselves, but I have my doubts that is possible.

**Comment by liuy97** [comment]
[Angular Compiling](https://www.ag-grid.com/best-angular-2-data-grid/index.php)

`Angular Compiling is NOT supported inside ag-Grid for Angular 2.`

`So, long story short, until Angular 2 is out of beta and someone can provide me with the best practice approach for using the Angular 2 compile service, ag-Grid won't support internal Angular 2 bindings.`

It has to been mentioned here.

**Comment by hildeorten** [comment]
Inhouse, Maria and Thor on DBH might know something about Angular 2. You
may try to ask them

liuy97 skrev den 24.06.2016 12:55:

> Angular Compiling
> https://www.ag-grid.com/best-angular-2-data-grid/index.php
> 
> |Angular Compiling is NOT supported inside ag-Grid for Angular 2.|
> 
> |So, long story short, until Angular 2 is out of beta and someone can
> provide me with the best practice approach for using the Angular 2
> compile service, ag-Grid won't support internal Angular 2 bindings.|
> 
> It has to been mentioned here.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/68#issuecomment-228316393,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tqA1YERe6NNmbFcY0hdCfV0FH-hqks5qO7eOgaJpZM4I80Lh.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by liuy97** [comment]
@hildeorten ,

No, I didn't ask questions about Angular 2. This suggested grid tool has this problem using Angular 2.

**Comment by liuy97** [comment]
reduplicated at #74
