### ISSUE TITLE
When selecting an existing entry for a Missing value category, the editor populates more than one field with that value.

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#680]
When selecting an existing entry for a Missing value category (e.g. 'Don't know' in the screenshot), the editor populates more than one field with that value.

This corresponds to issue 18 in the QDDT post v1 feedback log

**Comment by loucasal** [comment]
![Issue #18](https://user-images.githubusercontent.com/25279797/59268985-d541c480-8c45-11e9-81a2-65c3ea35ab3e.PNG)

**Comment by StigNorland** [comment]
It is still there, but easier to get around, will not be fixed to first release.
