### ISSUE TITLE
Question text - should be possible to enter less than 5 letters

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#681]
It is currently not possible to enter question items shorter than 5 letters. We currently have three examples of this rare occurrence, where the items in a battery simply read 'PDF', 'Wiki' and 'JPG'. I have worked around this for now by adding extra spaces.

This corresponds to issue 23 in the QDDT post v1 feedback log

**Comment by StigNorland** [comment]
hopefully, I will have time to expand responsedomain, so that you can make a grid or battery
