### ISSUE TITLE
Activity feed

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#685]
A feature that could help streamline work on large question modules is an 'Activity feed'. Ideally this would be on a separate page and would display the following information:
- Concepts added/removed/edited
- Attachments uploaded
- Comments added/edited
- Question items linked/unlinked to concepts

This corresponds to issue 29 in the post v1 QDDT feedback log

**Comment by StigNorland** [comment]
https://qddt-test.nsd.no/changelog
