### ISSUE TITLE
Error code when clicking on PDF icon

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#686]
When clicking on the 'PDF' icon to export a version of the ESS10 Democracy module, an error 'Error code 406, undefined' is sometimes displayed.

This corresponds to issue 31 in the post v1 QDDT feedback log

**Comment by loucasal** [comment]
We are still seeing this error in production. Can you confirm if a fix for this will be included in the next release, and also what would be an efficient workaround in the meantime?
