### ISSUE TITLE
ResponseCardinality in responsedomains

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#69]
All responsedomians need to specify ResponseCardinality. (min max value (stored as string))
ResponseCardinality tells us how many valid responses is allowed in a responsedomain.

min 1 max 1 -> have to give one answer and one only.
min 0 max 1 -> optional to answer, but maximum one anwser.
min 2 max 8 -> multiple choice, have to give atleast 2 answers, maximum 8.
When maximum  >1 it is multiplechoice, and drawing of responsedomain should keep with designs guides.

**Comment by StigNorland** [comment]
This also have implications on how to draw the responsedomains in questionItems
See https://github.com/DASISH/qddt-client/wiki/Usage-of-inputLimit-responseCardinality-in-different-classes

**Comment by hildeorten** [comment]
Input from HO/KKS:

-A response is never required, implies min should always start at 0.

Code lists, category domains:

```
-min 0 max 1

-min 0 max 2

-min 0 max 3

-min 0 max#element
```

All other response domains

```
-min 0 max 1
```

Stig Norland skrev den 24.06.2016 11:31:

> This also have implications on how to draw the responsedomains in
> questionItems
> See
> https://github.com/DASISH/qddt-client/wiki/Usage-of-inputLimit-responseCardinality-in-different-classes
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/69#issuecomment-228301251,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tjYRMgozBNVe66bJIL1plj3VAPMMks5qO6PXgaJpZM4I9mov.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
If that was the case, minimum would be redundant information.
in online surveys, you may want to keep it on min=1 especially when you have missingvalues at hand.
It is actually very common in online surveys to require a response.

**Comment by hildeorten** [comment]
- In most academic surveys it is woluntary to answer each single question.
  min value must be 0 to facilitate this.
- DDI has min value. This needs to be provided. 0 could be default min
  value in the system

Stig Norland skrev den 24.06.2016 13:07:

> If that was the case, minimum would be redundant information.
> in online surveys, you may want to keep it on min=1 especially when
> you have missingvalues at hand.
> It is actually very common in online surveys.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/69#issuecomment-228318496,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tuWKUV2FDEmtx58mikPYwIZ99P_Hks5qO7pXgaJpZM4I9mov.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
Your response sounds like minimum always **must** be 0, and therefore should be hidden or locked, which would limit its usage. default value will be min 0 max 1, but it should be possible to change this in the tool to whatever the user wants to.
