### ISSUE TITLE
UI glitch with ToC anchors

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#692]
The ToC in the right-hand sidebar of the list of concepts can quickly bring the user to the desired concept. However, after the user clicks on a concept, the header of the 'destination' concept is hidden behind the top navigation bar. The effect is misleading for the user, who cannot immediately identify its exact position in the list of concepts and is often led to scroll away.
Clicking on a concept should make the concept name appear in front of the user.

**Comment by StigNorland** [comment]
This is an known bug in Angular, and will be fixed in a future release of the framework
