### ISSUE TITLE
Revisit concept number/name styling

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#698]
In PDF exports, the concept number is currently presented more prominently than the concept name, which is counterintuitive. We would expect this to be the other way around, or possibly name and number with the same style. Perhaps different styles could be tested to see which one is more suitable.
Please refer to the PDF file shared via email.

**Comment by StigNorland** [comment]
![image](https://user-images.githubusercontent.com/3939393/48804064-eb248200-ed13-11e8-82df-81e057d8a4b2.png)
Maybe like this?

**Comment by loucasal** [comment]
How about the following style?

Concept: _ConceptName_ (complex/simple)
Sub concept: _SubConceptName_

(simple concepts being those with no sub concepts)
