### ISSUE TITLE
QuestionItem create

### ISSUE THREAD

**Issue by StigNorland** [DASISH/qddt-client#72]
the easiest way to add a question item to the model, is to add it to a Concept, and save the concept.

see https://github.com/DASISH/qddt-client/wiki/QuestionItem

**Comment by hildeorten** [comment]
But conceptually QuestionItem is an important element in its own.
It is not a child of concept and should be versioned independently

Stig Norland skrev den 24.06.2016 14:21:

> the easiest way to add a question item to the model, is to add it to a
> Concept, and save the concept.
> 
> see https://github.com/DASISH/qddt-client/wiki/QuestionItem
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/72, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tmC12gpBBz1EulnnbN9iGLcC0i7Mks5qO8vQgaJpZM4I9t8L.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
This has nothing to do with how it is conceptually, just how to save an
item with its relationships.

Stig

**Comment by liuy97** [comment]
This bug has been fixed at #65. If it does not work, write comment here.
