### ISSUE TITLE
PDF exports do not indicate the presence of external aids, nor show their content

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#727]
We just tested (on QDDT-test) the creation of a publication including constructs with external aids. We noticed that the presence of external aids is not shown in the PDF export, nor is their content visualised. Would it be feasible to display this in the PDF?

For the moment, we will work around this limitation by copying/pasting key information from external aids (e.g. recommendations based on analysis of pre-testing data) into the relevant constructs (and possibly other components) as comments.

**Comment by StigNorland** [comment]
It will be very complicated to include external content into the report, it can be anything.
Could add references to the content (clickable in the digital pdf report).

**Comment by StigNorland** [comment]
I can insert link to them, but it would be quite complicated to embed different kind of content into a pdf
