### ISSUE TITLE
Categories - update of view required

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#73]
@liuy97 
Issue a): View «Categories/NEW: When entering text under “Label” the text appears also under “Name” in uppercase. Can you remove «Name» from the view and make sure that no text will be stored under “Name” in the database.

Issue b): View “Categories/Edit”: Please also remove the fields “Name” and “minimum/maximum” from the view corresponding to the view “NEW”. Furthermore should “Reason for Change” be optional. Type of change is correctly mandatory in the tool.

**Comment by StigNorland** [comment]
Note that minimum/maximum are for NUMERIC/DATETIME & TEXT, since they no longer is in this view, it isn't needed there anymore.
