### ISSUE TITLE
Error when adding missings to existing item

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#733]
**To Reproduce**
1. Go to https://qddt.nsd.no/questionitems/9099ff31-2bbf-4f02-aa4a-12c0aa87a661
2. Replace the response domain
3. Try to add DKREF as missing

Screenshot attached.
![adding missings](https://user-images.githubusercontent.com/25279797/72556529-ba4bc880-3896-11ea-8ec3-cea5a0c59397.png)

**Comment by loucasal** [comment]
The same error is displayed when trying to add new categories to an existing set of missings. Should we open a separate ticket for that?

**Comment by StigNorland** [comment]
No need it has the same  root cause
