### ISSUE TITLE
'Get latest' always increases domain version number

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#736]
**To Reproduce**
1. Open an existing question item with a response domain attached
2. Verify that the response domain in use is already the latest version
3. Click on the 'Get latest' button
4. See that version number is increased at each click, even if no updated version exists

**Comment by StigNorland** [comment]
I am not sure this is a bug or a feature.

If you have just a simple responseDomain, it will fetch the latest version of this (and version updates to the correct (latest) version of this RD.

However, when you use a mixed responseDomain, it will try and fetch latest version of the "subdomain" and this will automatically increase the version of the mixed responseDomain by 1.
