### ISSUE TITLE
Cannot see full concept ToC in latest version

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#739]
1. Open the list of concepts for a module with a large number of concepts (e.g. ESS10 > Digital Social Contacts in Work and Family Life)
2. It is not possible to scroll through the full concept ToC - only the top part is displayed.

Tested on Firefox 72.

**Comment by StigNorland** [comment]
There are some strange behavior with Cascading Styles Sheets, and I have already tried to fix this.
However, it is great that you report it.
