### ISSUE TITLE
Overview page for categories

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#74]
@liuy97 

Please create an overview page for categories like currently exist for the question texts in the current version of the tool, see https://qddt.nsd.no/Questions.
Please add search and sort for the list.

**Comment by liuy97** [comment]
# How to use it

When you visit category page, you will get a list of categories with pagination. The page also supports for searching from the current table and sort ascending on **label** or **description**. A detail information will be showed by clicking **detail** button or doubleclicking one row, where editing and displaying revisions. You can test it via my machine.

# Need some input from users(here @hildeorten and Benjamin).
- Do you want to get searched results from backend server or only search the showed categories in the table?
- What kind of **sort** do you want to support?

**Comment by StigNorland** [comment]
Sort and paging from the server.

**Comment by liuy97** [comment]
@StigNorland ,
Please update API wiki regarding how to request sort elements on a specific field, such as label or description.
