### ISSUE TITLE
Full list of concepts not loaded in latest version

### ISSUE THREAD

**Issue by loucasal** [DASISH/qddt-client#740]
1. Open the list of concepts for a module with a large number of concepts (e.g. ESS10 > Digital Social Contacts in Work and Family Life).
2. Scroll to the bottom of the page and see that the list of concepts stops before the expected end, i.e. not all concepts are displayed.

Tested on Firefox 72.

**Comment by StigNorland** [comment]
I have put a limit of 100 (top) concepts in a module.

Reason is for performance, loading more elements into your browser isn't a good idea.

If time permit I will change this to a page loading mechanism, I hope 100 Concepts in a Module is enough.
