### ISSUE TITLE
Error when saving new response domains

### ISSUE THREAD

**Issue by JenniferMcGuiness** [DASISH/qddt-client#758]
When trying to save a new response Domain I am getting the error message 'Error code 500, Object was badly formed"

![image](https://user-images.githubusercontent.com/78354026/106450629-56824680-647d-11eb-8b6a-3bd5e1f5a433.png)

**Comment by StigNorland** [comment]
When you type into a “category search”, you’ll either find a Category to use  (`click `or `<enter>` to select)

![image](https://user-images.githubusercontent.com/3939393/106723709-b0167c80-6607-11eb-949e-b5288e147a56.png)

Or you have entered in a Category that still does not exists

![image](https://user-images.githubusercontent.com/3939393/106723753-bc023e80-6607-11eb-813c-7950d2353207.png)

You will need to press `<enter>` (and confirm the creation of this entity) to save a new entry
(the blue border indicate a new entry).

If there is no confirmation when you press `<enter>`, you will need to `click `inside the blue border to select the control and then press `<enter>` again.
