### ISSUE TITLE
refactor UI of response domain

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#76]
@hildeorten,

Put managed representation and response domain together.

UI of response domain will support scale domain and code domain for testing. The scale domain will specify the scale range and some anchor categories. The code domain will specify each code with one category.

Missing domain has be supported in this UI. If a missing domain exists, a mixed domain will be used for representing this response domain.

Reusing **maybe** is involved during this operation if it can be supported.
- [x] One entry for response domain where you can select the type of
  domain. Then one page for each selected domain.
- [x] Start with code domain and scale domain, numeric domain
- [x] Create a [Code domain](https://github.com/DASISH/qddt-client/wiki/qvdb-code-domain) 
- [x] Create a [Scale domain](https://github.com/DASISH/qddt-client/wiki/qvdb-scale-domain)
- [x] Create a new Missing code domain (have **not** implemented yet)
- [x] Create a [text domain](https://github.com/DASISH/qddt-client/wiki/qvdb-text-domain)
- [x] Create a numeric domain
- [x] Create a mixed domain (have **not** implemented yet, using missing category instead until now, Refs #83)

**Comment by hildeorten** [comment]
Comment, HO:

For an overview of the different response domain types planned to be
used, please see the document
https://github.com/DASISH/survey-tools-metadata/blob/master/core-domain-model/QVDB%20core%20domain%20model%20and%20documentation%2C%20working%20document%20as%20of%202015-12-01.pdf

1)      One entry for response domain where you can select the type of
domain. Then one page for each selected domain.

2)      Start with code domain and scale domain, missing code domain and
mixed domain

2.1) Create a new Code domain:

```
           2.1.1. Select already created categories for the code domain

           2.1.2. Assign appropriate codes for the categories

           2.1.3. Hierarchical code lists should be possible, but
```

this has a lesser priority for now

2.1.4. It should be possible to use a sub-set of codes of a list or a
level of a hierarchical list, but this has lesser priority for now

```
           2.1.5. Add response cardinality controlled vocabulary
```

2.1.6 Add controlled vocabularies for recommended data type and generic
output format. Default = integer

2.1.7 Add classification level, attribute ("Nominal" | "Ordinal" |
"Interval" | "Ratio" | "Continuous")

2.2) Create a new Scale domain:

```
           2.2.1. Select anchor point categories for use in the scale

           2.2.2. Define number range – High, Low

           2.2.3  Attach ancherpoint categories to some ( or all )
```

of the scale values

```
           2.2.4  Define degree of slope from horizontal of
```

dimension, DDI attribute integer

```
           2.2.5  Allow controlled vocabulary for type of scale
```

2.1.6. Add response cardinality controlled vocabulary

2.1.7 Add controlled vocabularies for recommended data type and generic
output format.  Default = integer

2.3) Create a new Missing code domain:

2.3.1. Select already created categories for the code domain

```
           2.3.2. Assign appropriate codes for the categories
```

2.3.3 Add controlled vocabularies for recommended data type and generic
output format. Default = integer

2.3.4  Allow controlled vocabulary for type of scale

In the mixed domain several response domains can be added, for example a
code domain and a missing code domain. This can be done in question
item. Another example can be to attach a text domain to a specific
category of a code domain, but this can wait for now.

_Reusing of response domains should be possible_

**

liuy97 skrev den 05.07.2016 14:22:

> @hildeorten https://github.com/hildeorten,
> 
> Put managed representation and response domain together.
> 
> UI of response domain will support scale domain and code domain for
> testing. The scale domain will specify the scale range and some anchor
> categories. The code domain will specify each code with one category.
> 
> Missing domain has be supported in this UI. If a missing domain
> exists, a mixed domain will be used for representing this response domain.
> 
> Reusing _maybe_ is involved during this operation if it can be supported.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/DASISH/qddt-client/issues/76, or mute the thread
> https://github.com/notifications/unsubscribe/AJu4tt2IMbv-ApeTcuxm0GzwjD5iydbjks5qSkx3gaJpZM4JFD7C.

## 

Hilde Orten
Spesialrådgiver/Special Adviser
Tel: +47 55 58 89 30
nsd.no http://nsd.no | twitter.com/NSDdata http://twitter.com/nsddata

**Comment by StigNorland** [comment]
managed representation and response domain are not conceptually or technically the same.
managed representation works as templates
and response domain are manifestation of those templates.

**Comment by StigNorland** [comment]
http://www.ddialliance.org/Specification/DDI-CV/DataType_1.0.html

**Comment by liuy97** [comment]
This issue is to improve the user workflow. The current workflow requires users to create a managed representation (which is actually a **category** in your implementation) firstly before creating a response domain. This process is too confused, according to user feedback. This issue plans to merge these steps. No one believes that managed representation and response domain is same.

Secondly, your given link is not helpful to understand your conclusion.

Thirdly, when it comes to DDI 3.2 itself, a response domain has no direct relationship with  [ManagedRepresentation](http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/schemas/reusable_xsd/elements/ManagedRepresentation.html). For example, [scale domain](http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/schemas/datacollection_xsd/elements/ScaleDomain.html)

@kksnsd, @hildeorten

**Comment by hildeorten** [comment]
@liuy97 
Issue #76
Stig writes:
managed representation and response domain are not conceptually or technically the same.
managed representation works as templates
and response domain are manifestation of those templates. 

I agree with Stig that conceptually a ManagedRepresentation is one thing and that ResponseDomain is a particular manifestation.
But now the ManagedRepresentation in the DDI and in the tool are two different things. ManagedRepresentation in the tool looks to me to equal CategorySchemes in DDI.
Individual categories from these lists can then be attached to codes and values as required at the ManagedRepresentation stage in DDI. These representations are useful reusable entities. In the tool the link between categories and codes or values is done at the ResponseDomain level. But as ResponseDomain is independent and reusable I hope that this way of organizing is ok (ResponseDomain thus representing the different ManagedRepresentations in DDI + elements included in ResponseDomainReference).

Suggestion for solution/workflow: 
Create CategorySchemes (now called ManagedRepresentations in the tool) in the same window as the ResponseDomain, but version these independently. Then create the response domain.

NB: Yong, the link Stig sent is to the controlled vocabulary for RecommendedDataType for the response domain, see 2.1.6 in my comment above. In terms of DDI 3.2, in our conceptual model ManagedScaleRepresentation has a relationship with response domain using ScaleDomainReference

**Comment by liuy97** [comment]
Refs #82, A missing response domain will not be supported, because the backend API does not support it. Instead of a missing response domain, a missing category will be supposed to use in Backend API.
