### ISSUE TITLE
DDI usage in the QDDT and QVDB

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#78]
DDI offers different solutions but for these tools we made a selection, and the elements and relationships we would like to make possible are described in the QVDB common metadata model working document:

https://github.com/DASISH/survey-tools-metadata/blob/master/core-domain-model/QVDB%20core%20domain%20model%20and%20documentation%2C%20working%20document%20as%20of%202015-12-01.pdf

Some work remains to complete the details for the QVDB. Our DDI output should be this or a subset of this. So please use this when thinking in terms of- or refering to DDI usage by the tools

**Comment by liuy97** [comment]
I moved scale domain and code domain to wiki. Convert them to web pages for being easy to refer to them.
