### ISSUE TITLE
testing front end

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#79]
@sarah-city, 
# URL

[qddt-client](http://dasish.github.io/qddt-client/)
# Update

Refs #76 , #74, #60

Refactoring response domain is still working in progress. Now it supports scale domain and code domain. Creating, editing and previewing can be supported.

For scale domain, **begin** and **end** have to be filled, such 1 and 3 respectively. The number of **anchor** stands for how many anchor will be given in scale domain, such as 2. The code of the anchor will be equal to the specified scale point value.
# Other

This issue will be used to notify any update on http://dasish.github.io/qddt-client/. Any error related to it (such as accessing error) can be written here using comment. Any comments/notes on front end will be supposed to create a new issue, assigning to Benjamin.

**Comment by liuy97** [comment]
Refs #76,

update, adding numeric domain and showing history of response domain.

**Comment by liuy97** [comment]
Refs #75,
- add showing rational code at level 1 and level 2
- add tooltips for rational codes
- add save as new-based on and save as new

**Comment by liuy97** [comment]
Refs #69,
- add response cardinality. when multiple choices required in code domains, checkboxes will be used. When the maximum choices are reached, users will not choose more until unselecting at least one.

**Comment by virginia-ros** [comment]
Hi @liuy97,
is there any way I can see these things you are implementing? I'm new in development and might need some help to catch up
thanks

**Comment by virginia-ros** [comment]
I think I got it, is it in your front end? 
http://liuy97.github.io/

Thanks :)

**Comment by liuy97** [comment]
Yes. All changes are listed at [commits](https://github.com/DASISH/qddt-client/commits/devel). All the commits give the related issues, where you can discuss or report problems.

**Comment by virginia-ros** [comment]
Thanks, I'm learning a lot about this but I still might ask stupid questions for a while :)

**Comment by liuy97** [comment]
No problem. We also need user feedbacks to improve the front end.

**Comment by virginia-ros** [comment]
That's my job so, we'll talk often

**Comment by liuy97** [comment]
Refs #74,
implement an advanced pagination.

**Comment by liuy97** [comment]
Refs #84,
add robot fonts

**Comment by liuy97** [comment]
Refs #85

**Comment by liuy97** [comment]
Refs #88

**Comment by liuy97** [comment]
Refs #86,
Now searching categories will not work until the backend at qddt.nsd.no is updated.

**Comment by liuy97** [comment]
Refs #92

**Comment by liuy97** [comment]
Refs #76 , add a text domain.

**Comment by liuy97** [comment]
Refs #93, fix null value.

**Comment by liuy97** [comment]
Refs #77, refactor question UI

**Comment by liuy97** [comment]
Refs #96

**Comment by liuy97** [comment]
Refs #102

**Comment by liuy97** [comment]
Refs #103

**Comment by liuy97** [comment]
Refs #95, create a new category when non-existing.

**Comment by liuy97** [comment]
Refs #75, fix demo according to feedback. 

A possible UI for changes are designed. Any feedback for it will be written in #99.

**Comment by liuy97** [comment]
Refs #118 , fix empty name of category schemes.

**Comment by liuy97** [comment]
Implement a versioning comparison.

**Comment by liuy97** [comment]
Refs #113

**Comment by liuy97** [comment]
Refs #113 , change UI of remove button.

**Comment by liuy97** [comment]
Refs #120

**Comment by liuy97** [comment]
Refs #124

**Comment by liuy97** [comment]
Refs #105

**Comment by liuy97** [comment]
Refs #129

**Comment by liuy97** [comment]
Refs #111

**Comment by liuy97** [comment]
Refs #108

**Comment by liuy97** [comment]
Refs #140, 
Refs #115, adding deleting button (not work actually).

**Comment by liuy97** [comment]
Refs #138

**Comment by liuy97** [comment]
Refs #130

**Comment by liuy97** [comment]
Refs #145

**Comment by liuy97** [comment]
Refs #147 , reduplicate this problem

**Comment by liuy97** [comment]
Refs #145

**Comment by liuy97** [comment]
Refs #153, #154 , #155 and #156

**Comment by liuy97** [comment]
Refs #148

**Comment by liuy97** [comment]
Refs #135

**Comment by liuy97** [comment]
Refs #161

**Comment by liuy97** [comment]
Refs #163

**Comment by liuy97** [comment]
Ref #110, #165 , demo support for question construct.

**Comment by liuy97** [comment]
Refs #142

**Comment by liuy97** [comment]
Refs #168
