### ISSUE TITLE
When do you think I could see what I input?

### ISSUE THREAD

**Issue by virginia-ros** [DASISH/qddt-client#80]
Hi,

I've been inputting concepts from round 7 immigration module. However, I cannot see anything and don't know what I have inputted or not. When do you thing that would be possible? 

Thanks, 

Virginia

**Comment by liuy97** [comment]
I can reduplicate this problem at qddt.nsd.no. No concept can be created, because the backend reported an error message.

**Comment by virginia-ros** [comment]
Ok, that's fine, I wasn't sure if it was just me. Can you let me know when it is sorted?
Thanks!

**Comment by liuy97** [comment]
This problem will be not fixed unfortunately until next week when the backend developer comes back from the holiday.
