### ISSUE TITLE
How to create a mixed domain?

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#83]
Refs #76

How to create a mixed domain?

**Comment by StigNorland** [comment]
it was already implemented before I went on holiday, what happened?

**Comment by liuy97** [comment]
Same to missing response domain. The problem is that mixed domain is a group of response domains. [**Managed Representation**](url) can only include a group of categories. Is it right?

**Comment by hildeorten** [comment]
@liuy97 @StigNorland 

Mixed domain as in DDI will be included in later versions of the tool
