### ISSUE TITLE
Domains: problems with searching categories

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#86]
When biulding response domains (scale and codecomain) only some categories are shown or are searchable.

Example: Category "Extremely dissatisfied" is not found in the list

**Comment by liuy97** [comment]
The current implementation does not support getting results of searching. If implementing it, I need some information from you (or users).
1. Which fields do you want to search?
   [Search API](https://github.com/DASISH/qddt-client/wiki/Api-queries) only supports searching on **Name**.
2. Do you need pagination for searching result?

**Comment by BenjaminNSD** [comment]
The search function depends on the content. When searching for categories the user will primary search for the "Label" of the category. The search function should be extended later on (adding version and other useful items depending on the element)

The results should be shown in a scroll down list as it is now, but it should not be limited to 20 hits as it is now. The number of hits must be increased.

Example: User types in "Mo" end receives a list with 20 hits. I'd prefer to show these hits in a long scroll down list rather then pagination for searching result. We should discuss this next week.

**Comment by StigNorland** [comment]
Always pagination.

**Comment by StigNorland** [comment]
and you can change the number of hits on a page to whatever....

**Comment by BenjaminNSD** [comment]
That's good!

**Comment by liuy97** [comment]
@BenjaminNSD, searching at backend does not work as expected. So It cannot be implemented now.
