### ISSUE TITLE
How to handle dublicate items, for example duplicate categories

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#87]
Should we allow duplicates in the tool?

Example for duplicate categories:

"Completely able" is entered twice in the tool (no difference, same version 1.0). We should at least have a warning which pops up?

**Comment by virginia-ros** [comment]
Yes, we have been talking about this, and it's the problem we might face when allowing entering the questions/categories from the "concept". We thought that, when entering a new category/question text, the tool should look for one that already exists if it is possible. That's the whole point of re-usability isn't it? thanks!

**Comment by StigNorland** [comment]
Duplicate chech in the backend,

**Comment by StigNorland** [comment]
needs testing, have been implemented
