### ISSUE TITLE
Versioning/time stamp is not working in several elements

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#90]
When clicking the versioning icon nothing happens (only Code Domain, working fpr the other)

**Comment by liuy97** [comment]
It works at my local machine. No error happens. The cause maybe is that the information has lost at the backend.

**Comment by StigNorland** [comment]
if nothing is happening, it is because front end crashed. (a refresh will sort that out)

In order to replicate the error we need more information about what you tried to do.

**Comment by StigNorland** [comment]
It appears to be an issue with elements not having a responding copy in the revision system.
By removing these elements from DB, we can fix that.

**Comment by BenjaminNSD** [comment]
Do you mean all elements where the time stamp is not working should be deleted/removed?

Example ESS4: "Concept Risk perception" has a time stap while "Beliefs about welfare state sustainability" has none. Should "Beliefs about welfare state sustainability" be deleted? And how, manually by the user or systematically?

**Comment by BenjaminNSD** [comment]
The time stap doesn't work for question items at all in http://liuy97.github.io/

**Comment by StigNorland** [comment]
in version history, the fetching of hierarchies don't behave identically with the rest of the api.
by applying  @JsonManagedReference and  @JsonBackReference
we can avoid circular references in the serialization of the json object.
