### ISSUE TITLE
Categories: Edit view: Uppercase of Label?

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#92]
When clicking the Edit button under categories the label appears in uppercase. Is this just the way it's displayed or does the text come from another item? In previous versions of QDDT the Label was automatically copied to Name in uppercase. Has this been changed in the current version? I can't controll that since the Name has been removed from the Front End as it was requested.

**Comment by liuy97** [comment]
The name is set automatically with label in uppercase. The category title in list is category's name. Do you need set it to category label?

**Comment by BenjaminNSD** [comment]
"Name" should not be used at for categories at all. The category title can be the Label.

Is it possible to clean the information on Name for all categories in the system without changing the business version?

**Comment by liuy97** [comment]
I can hidden "Name" of category at front end. However, what you said needs some work at the backend.

**Comment by BenjaminNSD** [comment]
Name is already hidden from the front end, but it's important for the future when it comes to XML output. We should clean the information on NAme, but it has not priority now.

**Comment by StigNorland** [comment]
We are not going to do anything about name, it will stay where it is.
Front end may ignore this field entirely, and continue to use label.
If anything is going to change, label will be removed as it is not needed, and frontend will show the field name, and call it whatever is convenient for the end user.

**Comment by BenjaminNSD** [comment]
I think it has to be discussed with Hilde next week.

Important is that only Label is shown in the frontend (as it is today) and that this information will be used in the contentelement "Label" in the DDI-XML export in the future.

**Comment by StigNorland** [comment]
Name can't be removed from the object, it is as simple as that.
If someone is worried about duplicating information the field called label can be removed, and the information stored there moved to the field name. What we call "name" in the front end will be exactly what you like it to be, be it 'label', 'text' or something else entirely. 
But this is strictly speaking internal mechanics, and not something you should need to worry about.

**Comment by StigNorland** [comment]
think we have solved this by now.
