### ISSUE TITLE
Non responsive ESS7 immigration module

### ISSUE THREAD

**Issue by virginia-ros** [DASISH/qddt-client#93]
I might have broken the tool, the immigration module is non responsive, non of the icons seem to do things...

**Comment by liuy97** [comment]
Sorry. This is a bug. Now it's fixed at http://liuy97.github.io/ . The site (qddt.nsd.no) will not be fixed until next update.

**Comment by virginia-ros** [comment]
Thank you! I'll work from your front end then :)
