### ISSUE TITLE
Category Scheme

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#97]
Refs #76,

`This issue is to improve the user workflow. The current workflow requires users to create a managed representation (which is actually a category in your implementation) firstly before creating a response domain. This process is too confused, according to user feedback. This issue plans to merge these steps.`

Now the category scheme is hidden (the front end will create one automatically) when creating a response domain.

Whether is category scheme to appear in response domain for reusing?

**Comment by hildeorten** [comment]
@StigNorland 

Will you please specify what in this response structure that covers- and is compatible with the DDI structure as specified in the QVDB core domain model and what is not? This impacts on how and what to use of this structure. I know reusable DDI CategorySchemes can be covered by this, which is good and useful but clarification is needed regarding the alternative options and if/how they can be mapped to DDI

**Comment by hildeorten** [comment]
Hi, for your info on related structures in DDI, please see the attachment,  @liuy97     @StigNorland 
[What happens where.docx](https://github.com/DASISH/qddt-client/files/388081/What.happens.where.docx)

**Comment by StigNorland** [comment]
StructuredMixedResponseDomain -> supported
ResponseDomainReference -> supported, TypeOfObject, not as DDI, but every object is by reference and you can look up and see, in an export, we can provide this.
ManagedRepresentations-> supported

[GenericOutputformat.xlsx](https://github.com/DASISH/qddt-client/files/486873/GenericOutputformat.xlsx)
