### ISSUE TITLE
Compare element to latest business version for versioning purposes

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#99]
@liuy97 

When more than one change is made between two business versions (for example in a questionitem both the responsedomain has been changed and a typo in the questiontext has been fixed), it is useful for the user to compare the latest business version and the proposal for the new version, to be able to version correctly by assigning the correct rationale codes and description. 

Could you please make a draft of how such a comparison could look like for questionitem for example (only on paper for example, for us to view). The user  should be able to see the latest business version and the new  proposal spread out in two paralell columns which can be scrolled down in parallell.

**Comment by hildeorten** [comment]
@liuy97 

The comparison should preferably be done by field level (DDI). If time now would great.
If no time for the first release this would be an issue to get back to for a future release

**Comment by liuy97** [comment]
Do you need me to write a proposal for this idea or implement it?

**Comment by liuy97** [comment]
What's "the first release"? Do you have any specific plan?

**Comment by hildeorten** [comment]
@liuy97 

It depends how much time each thing would take. If proposal takes much shorter time then make proposal first. Otherwise please implement.

First release must be the official release of the tool before City will start to use the tool. The tool should be operable in September according to the plan. This is still the goal. Date depends on the available functionality, and City and we (Knut) need to agree on it.

**Comment by liuy97** [comment]
It depends on whether the backend supports it. I needs to get the first business version before the current version. I cannot see any update in the Wiki now. Let me try to do some demos for this idea firstly. Your idea is very clear: two parallel columns for comparing DDI fields.

**Comment by hildeorten** [comment]
@liuy97 
Ok great :)

**Comment by hildeorten** [comment]
@liuy97 

Usecase should be Question Item. Please see attachement. The user should be able to see the latest business version and the new proposal spread out in two paralell columns which can be scrolled down in parallell.

ALl frontend elements (DDI elements) used  by the Item (also referenced elements like Concept or Responsedomain) should be compared. Elements with changes could be highlighted in a different colour for example.

[QDDT_Versioning_Compare.docx](https://github.com/DASISH/qddt-client/files/422476/QDDT_Versioning_Compare.docx)

**Comment by BenjaminNSD** [comment]
Please disregard the document above (QDDT_Versioning_Compare.docx). Comparison should be implemented in "Time stamp"-option as agreed in meeting 1. Sep
#135

**Comment by liuy97** [comment]
remove milestone according to the above comment.
